### 연습문제
- Doc2Vec 라이브러리 이용한 감정분석
- 데이터는 rationgs_train.txt 파일을 로드
    - 특수 문자, 2칸 이상의 공백의 문자를 제거하는 정규화 함수
    - document 컬럼의 데이터에서 중복 데이터를 제거
    - 빈 텍스트, " "가 존재한다면 해당 행 데이터도 제거
    - 상위의 5000개 정도 데이터를 이용
- 토큰화 함수 komoran를 이용
    - 필요한 품사 : NNP, NNG, VV, VA, MAG, XR만을 사용
    - 불용어 단어 : 하다, 되다. 이다, 것, 수, 거
- 데이터에서 독립(document), 종속(label) 변수로 데이터를 나누고 train, test 데이터셋을 나눠준다. 비율은 8:2
- Doc2Vec 객체를 생성하여 학습
    - 매개변수
        - vector_size = 200
        - window = 5
        - min_count = 2
        - dm = 1
        - negative = 5
        - seed = 42
        - epochs = 50
    - 학습 시키는 데이터는 X_train
- X_train, X_test -> 문자열 데이터 -> infer_vector() 함수를 이용해서 임베딩
- 고전 머신러닝 분류 모델을 이용하여 임베딩된 데이터를 독립 변수로 X의 데이터들을 종속 변수로 학습하여 예측
    - 정확도를 확인
    - LogisticRegression(max_iter = 2000, radom_state = 42)
    - LinearSVC(random_state = 42)
    - 두개의 모델을 사용하여 정확도가 좋은 모델을 선택

In [248]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC, SVC
from sklearn.metrics import classification_report, accuracy_score
from konlpy.tag import Komoran
from gensim.models.doc2vec import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
import re

In [193]:
data = pd.read_csv("../data/ratings_train.txt", sep="\t")
data.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [194]:
data['document'] = data['document'].fillna('')

In [195]:
# document의 중복과 빈 텍스트, " " 행 제거
data = data.drop_duplicates(subset=['document'])
data = data[data['document'].str.strip() != '']

In [196]:
# 문자에서 불필요한 글자들을 제거 (정규화)
def nomalize(text):
    # 특수문자 제외 , 공백에 대한 처리 
    text = re.sub(r"[^가-힣0-9a-zA-Z\s\.]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

data['document'] = [nomalize(text) for text in data['document'].values]

In [197]:
data = data[:5000]

In [198]:
# 형태소 분석 Komoran을 이용하여 토큰화 
komoran = Komoran()

# 특정 품사만 사용 
allow_pos = [ 'NNP', 'NNG', 'VV', 'VA', 'MAG', 'XR' ]
# 불용어 
stop_word = ['하다', '되다', '이다', '것', '수', '거']

def tokenize(text):
    tokens = []
    for word, pos in komoran.pos(text):
        if pos in allow_pos:
            # 길이를 체크하기 전에 동사, 형용사 에는 '다' 붙이기 활용
            if pos in ['VV', 'VA']:
                word += '다'
            if word not in stop_word and len(word) > 1:
                # allow_pos의 포함되어있고
                # stop_word에 포함되어있지 않으며
                # 단어의 길이가 1보다 큰 문자만 활용
                tokens.append(word)
    return tokens

tokenize_docs = [ tokenize(doc) for doc in data['document'].values ]
tokenize_docs

[['더빙', '진짜', '짜증', '나다', '목소리'],
 ['포스터', '초딩', '영화', '오버', '연기', '가볍다'],
 [],
 ['교도소', '이야기', '솔직히', '재미', '없다', '평점', '조정'],
 ['익살', '연기', '돋보이다', '영화', '스파이더맨', '늙다', '보이다', '커스틴 던스트', '너무나'],
 ['걸음마', '떼다', '초등학교', '학년', '영화', '반개', '아깝다'],
 ['원작', '긴장감', '제대로', '살리다'],
 ['반개',
  '아깝다',
  '나오다',
  '이응경',
  '길용우',
  '연기',
  '생활',
  '정말',
  '발로',
  '납치',
  '감금',
  '반복',
  '반복',
  '드라마',
  '가족',
  '없다',
  '연기',
  '못하다',
  '사람',
  '모이다'],
 ['액션', '없다', '재미', '있다', '영화'],
 ['평점', '낮다', '보다', '헐리우드', '화려', '너무', '길들이다', '있다'],
 [],
 ['눈물', '나서다', '죽다', '향수', '자극', '허진호', '감성', '절제', '멜로', '달인'],
 ['울다', '손들다', '횡단보도', '건너다', '뛰쳐나오다', '이범수', '연기', '드럽다'],
 ['담백', '깔끔', '좋다', '신문', '기사', '로만', '보다', '보다', '자꾸', '잊어버리다', '사람'],
 ['취향',
  '존중',
  '진짜',
  '극장',
  '보다',
  '영화',
  '가장',
  '재다',
  '감동',
  '스토리',
  '어거지',
  '감동',
  '어거지'],
 ['매번', '긴장'],
 ['사람',
  '웃기다',
  '바스코',
  '이기다',
  '락스',
  '바비',
  '이기다',
  '아이돌',
  '깔다',
  '그냥',
  '까다',
  '안달',
  '보이다'],
 ['굿바이 레닌', '표절', '이해', '갈수록', '재미없다'],
 ['이건', '정말', '깨알', '캐스팅', '질퍽', '산뜻', '내용', '구성', '깨알'],
 ['약탈', '위하다', '변명', '착하다', '절대'],
 ['심오', '있다', '그냥', '학생', '선생', '놀아나다', '영화', '절대'],
 ['보다', '웃다', '가능'],
 ['재미없다',
  '지루',
  '같다',
  '음식',
  '영화',
  '만찬',
  '만찬',
  '이야기',
  '있다',
  '음식',
  '보다',
  '재미',
  '있다',
  '이건',
  '보다',
  '없다',
  '음식',
  '별로',
  '나오다',
  '핀란드',
  '풍경',
  '별로',
  '나오다'],
 ['절대', '평범', '영화', '수작', '말씀', '드리다'],
 ['주제', '좋다', '중반', '지루'],
 ['짜르다', '납득', '없다', '그렇다', '그렇다', '끄다'],
 ['고추', '털다'],
 ['카밀라', '연기'],
 [],
 ['센스', '있다', '연출력', '탁월', '캐스팅', '90년대', '향수'],
 ['포스', '위력', '다시', '깨닫다', '검사', '연기', '정말', '좋다', '완전', '명품', '드라마'],
 ['쓰레기', '시간', '아깝다'],
 ['재밌다', '별점', '이리', '은고'],
 ['라도', '기대', '죄인', '죄인'],
 ['아직', '드라마', '인생', '최고'],
 ['패션', '대하다', '열정', '안나', '투어'],
 ['키이라 나이틀리', '연기', '대체', '정신', '장애', '장애'],
 ['작가', '정신', '나가다', '유령', '재미있다'],
 ['포스터', '있다', '보이다', '관객'],
 ['영화', '이렇다', '평가', '받다', '모르다'],
 ['단순', '은은', '매력', '영화'],
 ['알바',
  '내용',
  '없다',
  '무섭다',
  '거도',
  '없다',
  '웃기다',
  '거도',
  '없다',
  '완전',
  '싱겁다',
  '영화',
  '시간',
  '아깝다',
  '완전',
  '낚이다'],
 ['오다', '서리', '굶주리다'],
 ['정말', '들다', '보다', '보다', '방법', '없다'],
 ['윤제문',
  '멋지다',
  '배우',
  '발견',
  '소소',
  '일탈',
  '잔잔',
  '미소',
  '머금다',
  '음악',
  '조금',
  '아쉽다',
  '평점',
  '올리다'],
 ['평점', '속지', '마시', '시간', '낭비', '낭비'],
 ['리얼리티',
  '뛰어나다',
  '크다',
  '공감',
  '가다',
  '이민기',
  '캐릭터',
  '정신의학',
  '분노',
  '조절',
  '장애',
  '초기',
  '증상',
  '툭하면',
  '사람',
  '패다',
  '물건',
  '파손',
  '조금',
  '오바',
  '초반',
  '신선',
  '가다',
  '갈수록',
  '이민기',
  '정신',
  '상태',
  '공감',
  '불가'],
 ['마이너스', '없다', '보다', '영화', '수준', '북한', '만들다', '대다'],
 ['나다', '영화', '사랑합니다'],
 ['리스',
  '타르',
  '가르다',
  '용의',
  '주인',
  '이랑',
  '근친상간',
  '다니다',
  '소설',
  '제일',
  '멋지다',
  '자이',
  '니스',
  '드라마',
  '드래곤',
  '제일',
  '멋지다',
  '웃음',
  '감독',
  '토르',
  '다크 월드',
  '잡수다',
  '기본',
  '선방'],
 ['영화',
  '사람',
  '영혼',
  '어루만지다',
  '있다',
  '거치다',
  '세상사',
  '잠시',
  '잊다',
  '동화',
  '같다',
  '영화',
  '행복'],
 ['게이', '작다', '고추', '매운맛', '보이다', '진호', '간다'],
 ['이렇다', '가슴', '시리다', '보다', '드라마', '있다', '감동', '자체'],
 ['꼬마', '애가', '원한', '깊다', '그냥', '혼자', '나대다', '어쩌다'],
 ['재미있다'],
 ['좋다'],
 ['최고'],
 ['너무',
  '충격',
  '기분',
  '완전히',
  '꺼지다',
  '느낌',
  '활력',
  '없다',
  '너무나',
  '무겁다',
  '지독',
  '차갑다',
  '자비',
  '그저',
  '일본인',
  '상상력',
  '정말',
  '대단',
  '같다',
  '생각',
  '들다'],
 ['심심', '영화'],
 ['백봉기', '언제나', '오다'],
 ['보다', '그대로', '들어맞다', '예측', '카리스마', '없다', '악역'],
 ['불알', '나오다', '당황', '아무튼', '영화', '중간', '끝나다', '느낌'],
 ['평범', '함속', '아든', '평범', '일상', '조금', '밋밋'],
 ['보다',
  '계속',
  '보다',
  '전개도',
  '느리다',
  '주인공',
  '은희',
  '나오다',
  '소극',
  '모습',
  '짜증',
  '맨날',
  '언제',
  '끝나다',
  '기대',
  '전개',
  '빨리빨리'],
 ['사랑', '가슴속', '오다', '감정', '헤집다', '영화', '요정', '최고'],
 ['많다',
  '사람',
  '보다',
  '우리나라',
  '슬프다',
  '현대사',
  '단면',
  '대하다',
  '깊이',
  '생각',
  '사죄',
  '바로',
  '잡기',
  '위하다',
  '노력',
  '듣다',
  '보도',
  '연맹',
  '민간인',
  '학살',
  '이정',
  '이건',
  '명백',
  '살인',
  '살인자',
  '있다'],
 ['예전',
  '작품',
  '캐릭터',
  '에피소드',
  '재탕',
  '삼탕',
  '사골',
  '우려',
  '먹다',
  '내용',
  '가다',
  '시청률',
  '아예',
  '나오다',
  '이제',
  '중반'],
 ['김남길', '연기력', '초반', '몰입', '불구', '지루', '손예진'],
 ['재밌다', '비슷', '영화', '안보', '재미있다'],
 ['노래', '실력', '뽑다', '맞다', '박시환', '가면', '진짜', '망신'],
 ['일본', '영화', '유치'],
 ['이틀',
  '보다',
  '재밌다',
  '물건',
  '넣다',
  '조작',
  '열리다',
  '활짝',
  '열리다',
  '들어가다',
  '문자',
  '조작',
  '비번',
  '걸리다',
  '억지',
  '내용',
  '자체',
  '좋다'],
 [],
 ['달팽이', '빠르다', '재밌다'],
 ['어설프다', '전개', '어이없다', '결말'],
 ['부패', '로마노프 왕조', '기리다', '같다', '영화', '온몸', '항거', '러시아', '민중', '그저', '돌다'],
 ['내용', '전개', '무난', '편이', '보다'],
 ['매우', '실망'],
 ['한국',
  '영화',
  '흥행',
  '코드',
  '갈등',
  '갈등',
  '갈등',
  '화해',
  '감동',
  '평점',
  '남발',
  '흥행',
  '뻔하다'],
 ['아햏햏', '아햏햏', '아햏햏'],
 ['시작', '3분', '나오다', '리플릿', '사진', '보다', '불안'],
 ['단연', '최고'],
 ['감독', '영화', '만들다', '관객', '모르다', '엉망진창', '개진'],
 ['이건', '우뢰', '매다'],
 ['정말', '쓰레기', '영화'],
 ['진정', '위대', '영화', '최고'],
 ['별루'],
 ['내일', '기대'],
 ['조미', '좋아하다', '가요'],
 ['진짜', '까다', '부라리다', '쓰러지다'],
 ['성룡', '영화', '악인'],
 ['때리다', '걸스데이', '이혜리'],
 ['서기', '이쁘다'],
 ['완전', '재밌다', '백인', '공주', '귀여움'],
 ['인상', '영화'],
 ['세다', '스티', '완전', '추다', '정말', '재밌다'],
 ['재미있다', '영화'],
 ['클라라', '볼라', '화신'],
 ['진짜', '보다', '너무', '슬프다', '영화'],
 ['설정', '재밌다', '새롭다', '에피소드', '메인', '스토리', '차차', '나오다', '재밌다'],
 ['신카이 마코토', '작화', '카나', '연기', '대박'],
 ['재미없다', '진심', '캐스팅'],
 ['잔잔', '생각', '보다', '영화인', '같다'],
 ['감독', '고은님', '쓰다', '영화', '보다'],
 ['무섭다', '스토리'],
 ['영화', '억지', '노골적', '광고', '은은', '센스', '있다', '어떻다'],
 ['킬링타임'],
 ['크리스마스', '떠오르다', '영화'],
 ['재미있다', '보다', '매력', '행복'],
 ['음악', '완전히', '빠지다', '보다', '영화', '쪼다', '산만'],
 ['태어나다', '처음', '영화', '중간', '나오다', '불륜', '로맨스'],
 ['짜증', '아주', '전개', '짬뽕', '믹스', '음향', '무섭다'],
 ['솔직히', '나다', '별루', '덜다', '시간', '낭비', '느낌'],
 ['대박'],
 ['시청률', '기준', '패널', '가구', '거지', '명작', '드라마', '망치다', '서운'],
 ['내용', '이상해'],
 ['몬스터 주식회사', '3D', '재밌다', '보다'],
 ['내용', '전개', '너무나', '느리다'],
 ['소재', '흥미', '끌다', '이야기', '전개', '투박', '몰입'],
 ['절대', '보지', '마라', '쓰레기', '영화'],
 ['중국인',
  '특유',
  '과장',
  '허풍',
  '있다',
  '보이다',
  '안간힘',
  '쓰다',
  '노력',
  '가상',
  '고증',
  '현실감',
  '떨어지다',
  '설정',
  '거북',
  '도대체',
  '이렇다',
  '스스로',
  '대포',
  '장하'],
 ['그냥', '불법체류', '때려잡다', '영화', '좋다', '우상', '만들다', '미국', '따뜻', '설정', '이건'],
 ['2년', '주인공', '생애', '전부', '드러나다'],
 ['별점', '가자'],
 ['별로'],
 ['보다', '지나다', '남기다', '재미있다'],
 ['아니', '일다'],
 ['지나다', '다시', '보다', '영화', '다시', '보다', '순수', '사랑', '감동', '연기'],
 ['올레',
  '공짜',
  '있다',
  '보다',
  '허다',
  '스토리',
  '문제',
  '연기자',
  '전혀',
  '배역',
  '이랑',
  '어울리다',
  '상대',
  '배우',
  '따로',
  '같다',
  '이건',
  '연기자',
  '문제',
  '있다',
  '보다',
  '진심',
  '완전',
  '별로',
  '라미란',
  '아들'],
 ['너무', '욕심', '많다', '영화', '제대로', '보이다'],
 ['빵점'],
 ['아주', '쓰다'],
 ['아주', '모자', '라진'],
 ['영화', '도둑들', '뫼비우스', '같다', '나라', '만들다', '믿다'],
 ['온몸', '찌릿', '짜릿', '용기', '가지다'],
 ['정말', '재미있다', '교훈', '영화'],
 ['당시', '상황', '주제', '주입식', '긴장감', '있다', '재밌다', '전하다', '작품'],
 ['케이블', '그만', '나오다'],
 ['다르다', '차이밍량', '섞이다', '짬뽕', '그릇', '담기다'],
 ['여군', '재다', '없다', '건지', '재다', '없다', '재다', '없다', '질리다', '다이'],
 ['좋다'],
 ['한석규', '김혜수', '연기', '돋보이다', '영화', '모르다', '많이', '어설프다', '영화'],
 ['솔직히',
  '에볼라바이러스',
  '떠들석',
  '보다',
  '영화',
  '작품',
  '영화',
  '믿다',
  '힘들다',
  '정도',
  '정말',
  '만들다',
  '마지막',
  '후반부',
  '살짝',
  '아쉽다',
  '이정',
  '도면',
  '수작',
  '시간',
  '아깝다',
  '영화'],
 ['보다', '만해'],
 ['재미있다', '허풍', '떨다'],
 ['용가리', '진짜', '매다'],
 ['영화',
  '이제서야',
  '감히',
  '인생',
  '최고',
  '영화',
  '하나로',
  '꼽다',
  '있다',
  '작품',
  '어떻다',
  '살다',
  '위하다',
  '고민',
  '시간',
  '모건 프리먼',
  '나이',
  '들다',
  '여전히',
  '섹시'],
 ['작가', '별로', '내용', '진짜', '맨날', '그냥', '기대', '재방송', '혹시나', '없다', '진짜'],
 ['명작', '명작', '있다', '보다', '보다', '여운', '남다', '영화'],
 ['진짜',
  '조금',
  '보다',
  '상업',
  '영화',
  '못하다',
  '만들다',
  '아쉽다',
  '충분히',
  '재미있다',
  '개인',
  '조금',
  '잔인',
  '자극',
  '노출',
  '화끈',
  '어떻다',
  '국산',
  '영화',
  '많이',
  '아끼다',
  '보이다'],
 ['그만', '끌다', '이제', '끝내다', '지겹다', '지겹다'],
 [],
 ['드니', '연기', '일품', '맥스', '죽이다'],
 ['괜찮다', '작품'],
 ['너무', '좋다', '영화'],
 ['정말', '실망'],
 ['배우', '뜨다', '영화', '찍다', '뜨다', '진짜', '모르다', '면상', '보다', '알다', '자신', '모르다'],
 ['어린이', '좋아하다', '어리다', '동심', '멀리', '뜨다', '낫다'],
 ['무술', '들다'],
 [],
 ['크리스토퍼', '왈츠', '타란티노', '조합'],
 ['한국', '에선', '유명한', '외국', '상상', '초월', '유명', '영화'],
 ['오랜만'],
 ['아쉽다',
  '오늘',
  '방도',
  '보다',
  '방송',
  '대본',
  '완성도',
  '있다',
  '느낌',
  '받다',
  '요즘',
  '드라마',
  '막장',
  '지치다',
  '정말',
  '바른',
  '드라마',
  '악역',
  '그리',
  '심하다',
  '어이없다',
  '화이팅'],
 ['평점',
  '조절',
  '위원회',
  '나오다',
  '웃음',
  '김혜선',
  '내일이 오면',
  '순정',
  '순정',
  '역할',
  '정도',
  '해내다',
  '정말',
  '의외',
  '연기',
  '20년',
  '사람',
  '요즘',
  '사극',
  '벌어지다',
  '있다',
  '대하다',
  '연기',
  '논란',
  '왠지',
  '코미디',
  '의하다',
  '장면',
  '같다',
  '웃음'],
 ['영화', '끝나다', '멍하다', '보다', '한마디', '나오다', '같다'],
 ['공유'],
 ['상쾌', '발랄', '영화', '끌다', '소재', '유쾌', '해설'],
 ['소파', '치다', '앉다', '지키다', '보다', '이유', '없다', '작품'],
 ['로큰롤'],
 ['주되다',
  '타겟',
  '어린이',
  '일반',
  '논리',
  '통하다',
  '알다',
  '게임',
  '흥미',
  '요원',
  '주인공',
  '너무',
  '능력',
  '별로',
  '재미없다',
  '배경',
  '거슬리다'],
 ['뮤지컬 영화',
  '사운드',
  '녹음',
  '엉망',
  '추다',
  '내용',
  '뻔하다',
  '주인공',
  '목소리',
  '너무',
  '어울리다',
  '어제',
  '뛰다',
  '나가다',
  '참다',
  '진심',
  '말리다',
  '영국',
  '예산',
  '영화',
  '뮤지컬',
  '영화',
  '맘마미아',
  '10'],
 ['어리다', '나이', '보다', '좋아하다', '로맨틱', '코미디'],
 ['게이', '인줄', '모르다', '보다'],
 ['알바', '끄다', '절다'],
 ['영화', '받다', '보다', '알다', '영화', '배우', '스텝', '감독', '꼭두각시'],
 ['최악'],
 ['정말', '아름답다', '영화'],
 ['자극', '익숙', '현대인', '보다', '떼다', '힘들다', '연출력'],
 ['읽다', '당하다'],
 ['정말',
  '짜증',
  '극치',
  '보이다',
  '영화',
  '굉장히',
  '느낌',
  '뚱뚱',
  '못생기다',
  '남자',
  '연기',
  '시종일관',
  '보다',
  '고역',
  '흘러나오다',
  '잔잔',
  '클래식',
  '음악',
  '조차',
  '듣다',
  '싫다',
  '짜증',
  '정도',
  '상당히',
  '싫다',
  '영화'],
 ['감동', '감동', '정말', '최고'],
 ['별점',
  '아깝다',
  '얼마나',
  '내용',
  '진부',
  '나오다',
  '재밌다',
  '사람',
  '초딩',
  '죄송',
  '너무',
  '화가',
  '나서다',
  '보다',
  '없다',
  '보다',
  '그냥',
  '비판',
  '집기',
  '같다'],
 ['짜증', '내다'],
 ['돼지', '먹다', '닭목', '따다', '장면', '에선', '무당'],
 [],
 ['유치', '지루'],
 ['판타지', '가져가다'],
 ['윤종신',
  '복귀',
  '좋다',
  '이하늘',
  '도대체',
  '뽑히다',
  '없다',
  '참가자',
  '실력',
  '따지다',
  '심사',
  '위원',
  '인격',
  '실력',
  '쌓다',
  '오시',
  '그만'],
 ['광장', '작품', '옛날', '보고 싶다'],
 ['최고', '영화'],
 ['어리다',
  '시절',
  '너무',
  '무섭다',
  '재미있다',
  '보다',
  '추억',
  '판타지',
  '영화',
  '절대',
  '나쁘다',
  '금물',
  '지옥',
  '가요'],
 ['기존', '멜로', '영화', '형식', '탈피', '감정', '절제', '지나치다', '너무', '담백', '영화'],
 ['나다', '사랑비', '서주', '빠지다', '나다', '절대', '잊다', '후회', '도안', '할거'],
 ['이영화', '보다', '교훈', '남은', '인생', '화려', '나오다'],
 ['추억', '젖다', '좋다', '생각', '없이', '가볍다', '보다', '추천'],
 ['단순', '싸이코', '벗어나다'],
 ['만들다', '가요', '예전', '만들다', '다시', '개봉', '가요', '너무', '접하다'],
 ['사랑', '영화', '보고', '연잇다', '보다', '귀여워'],
 ['청춘 영화',
  '있다',
  '감성',
  '넘치다',
  '순간',
  '지나가다',
  '다시',
  '돌아오다',
  '순간',
  '무한',
  '젊음',
  '있다',
  '감성'],
 ['건담', '시리즈', '아직', '최고봉'],
 ['개코', '요즘', '갈수록', '코너', '달다', '재다', '웃음', '이안', '나다'],
 ['사다코', '서리다', '우물', '펀치', '감동'],
 ['후세',
  '사랑',
  '결정',
  '계기',
  '시간',
  '표현',
  '생명',
  '빼앗다',
  '이유',
  '시노',
  '출현',
  '연극',
  '알리다',
  '생각',
  '시노',
  '얼마나',
  '시랑',
  '노력',
  '보이다',
  '좋다'],
 ['새벽', '시간', '일본', '영화', '전부', '일본', '영화', '원래', '이러다'],
 ['강수연', '나가다', '최정원', '신음'],
 ['정말', '김혜성', '너무', '예쁘다', '이현진', '웃다', '정말'],
 ['가발', '쓰다'],
 ['화려', '이인상', '깊다', '배두나', '연기', '정말'],
 ['10대', '위하다', '성적', '호기심', '영화'],
 ['감동', '영화'],
 ['이건', '필요', '없다', '그냥', '닥치다', '보다'],
 ['각기', '사람', '재밌다', '멋지다', '사랑', '영화'],
 ['미국', '드라마', '파워', '정말', '수없다', '미묘', '사로잡다', '최고'],
 ['너무너무', '훈훈'],
 ['응답하라', '은지원', '원도', '스스로'],
 ['너무', '웃기다', '배꼽', '빠지다', '영화', '있다'],
 ['구성', '상당히', '부실', '영화', '네이버', '평점', '믿다', '없다'],
 ['끌다', '로드', '몰락', '가져오다', '오우삼', '헐리우드', '작품', '가장', '재미없다'],
 ['영웅본색', '연출', '인지', '현실', '제로', '영화'],
 ['작다',
  '하나에',
  '설레다',
  '학창',
  '시절',
  '그때',
  '느낌',
  '다시',
  '느끼다',
  '시간',
  '장면',
  '대사',
  '배경',
  '음악',
  '없다',
  '드라마'],
 ['진심', '재미', '없다', '너무', '평점', '높다', '화나다'],
 ['더럽다', '재미없다', '형태', '오다', '닿다', '허무', '완벽히', '지루', '영화', '영양가', '없다', '영화'],
 ['이승기', '정말', '연기', '조연', '연기', '정말'],
 ['현실', '현실'],
 ['오늘', '현충일', '특집', '프로', '보다', '매우', '훌륭', '작품'],
 ['의미', '동급'],
 ['제대', '보다', '재밌다'],
 ['영화',
  '보다',
  '마음',
  '휴가',
  '다녀오다',
  '느낌',
  '하지',
  '잔잔',
  '지루',
  '다시',
  '보다',
  '영화',
  '햇살',
  '가득',
  '부엌',
  '요리',
  '인상'],
 ['코믹', '좋다', '짜임새', '너무', '허술'],
 ['그때',
  '당시',
  '나라',
  '판타지',
  '로맨스',
  '없다',
  '아직',
  '신현준',
  '장군',
  '연기',
  '괜찮다',
  '한석규',
  '전성시대',
  '열리다',
  '영화',
  '이때',
  '한석규',
  '가다'],
 ['일단', '재생', '괴물', '같다', '서스펜스', '귀신', '같다', '흡입'],
 ['진짜',
  '댓글',
  '한번쯤',
  '영화인',
  '같다',
  '죽기',
  '직전',
  '소원',
  '들어주다',
  '보다',
  '죽기',
  '직전',
  '살다',
  '같다',
  '감동',
  '없다',
  '진짜',
  '영화',
  '발톱',
  '따라가다',
  '쓰레기',
  '영화',
  '와다',
  '실망'],
 ['시간',
  '밝다',
  '긍정',
  '드라마',
  '보다',
  '보기',
  '보다',
  '오버',
  '연기',
  '거슬리다',
  '연기',
  '너무',
  '홍혜정',
  '이그',
  '마도',
  '후련',
  '기도',
  '고시원',
  '나머지',
  '답답',
  '내다',
  '월요일',
  '해피',
  '보다'],
 ['정치인', '모순', '인가', '정치범', '모순'],
 ['어떻다', '상상', '대단'],
 ['어렵다', '전쟁', '대하다', '묘사', '모르다'],
 ['일본', '극장판', '만들다', '우리나라', '에선', '개봉', '하니', '이건'],
 ['개그콘서트', '보다', '전화', '끊다', '개그', '콘서트', '없애다'],
 ['한물', '동서양', '배우', '싸움판'],
 ['푸다', '기대'],
 ['세계', '최초', '반공', '애니매이션', '역사', '가치'],
 ['감각', '시각', '바라보다', '색다르다', '느낌', '사랑', '문학'],
 ['엄마', '무고', '감옥살이', '시키다', '시키다', '이해'],
 ['이영화', '제발', '보세', '감독', '미치다', '만들다', '정도'],
 ['신나다', '흑인', '음악', '아이스 큐브', '남다', '없다'],
 ['드럽다', '재미없다', '시간', '시간', '어쩌다'],
 ['그저', '한마디', '알리다'],
 ['진짜', '생생', '느끼다'],
 ['재밌다', '평점', '이상', '정도', '낮다'],
 ['옥소리', '프로필', '사진', '남기다', '가다', '완전', '대박', '진짜', '아우', '짜증'],
 ['드라마', '너무'],
 ['진짜', '너무', '좋다'],
 ['연기'],
 ['영화', '다시', '나오다', '그때', '시절', '나타내다', '같다'],
 ['중간', '정도', '보다', '대단'],
 ['까다', '제맛', '까다', '제맛'],
 ['소설', '재미없다'],
 ['액션', '영화', '범죄', '느와르', '영화', '범죄', '느와르', '영화', '실패작'],
 ['없다', '매력', '빠지다', '영화'],
 ['모녀',
  '토막',
  '살해',
  '살인자',
  '성애',
  '말이',
  '감동',
  '받다',
  '사람',
  '본인',
  '피해자',
  '감동',
  '받다',
  '진심',
  '묻다'],
 ['재밌다', '평점', '이렇다', '구리지'],
 ['보다', '아깝다', '진짜', '놓다', '진짜', '명작'],
 ['필름', '아깝다', '재미', '더럽다', '없다', '수준', '매미'],
 ['보다'],
 ['영화', '재미있다'],
 ['남주인공',
  '연기력',
  '짧다',
  '소리',
  '듣다',
  '너무',
  '힘들다',
  '매니저',
  '역활',
  '분이',
  '남주인공',
  '좋다',
  '생각',
  '들다',
  '정도',
  '영화',
  '자체',
  '적당히',
  '보다'],
 ['액션', '스릴러', '액션', '스릴', '없다'],
 ['완전', '스토리', '엉망', '완전'],
 ['영화', '전달', '모르다', '거리'],
 ['좋다', '영화'],
 ['더빙', '이상', '할머니', '월래', '익숙'],
 ['나오다'],
 ['부족'],
 ['정말', '그대로', '영화'],
 ['보다', '기억', '진개', '천카이거', '감독', '이름', '기억', '두다'],
 ['정은지', '언니', '연기', '노래', '부르다', '마지막', '웃다', '즐겁다', '보다', '트로트의 연인'],
 [],
 ['망하다'],
 ['아이', '시선', '보다', '전쟁', '보다', '내내', '가슴', '먹먹'],
 ['사람',
  '재미없다',
  '레알',
  '기대',
  '생각',
  '보다',
  '여자',
  '복순이',
  '다투다',
  '장면',
  '굳이',
  '없다',
  '생각',
  '몰입',
  '겁나다',
  '없애다',
  '어색',
  '보이다'],
 ['설정', '연속극', '같다', '느낌', '들다', '배우', '연기', '뛰어나다'],
 ['여주인공', '인터뷰', '지루', '죽다', '알다', '그냥저냥', '킬링타임', '스릴러'],
 ['박스',
  '오피스',
  '그냥',
  '몰아주다',
  '어떻다',
  '영화',
  '옛날',
  '90년대',
  '우뢰',
  '수준',
  '폭탄',
  '싸움',
  '가나',
  '폭탄',
  '나가다',
  '다르다'],
 ['감독', '여자', '보니', '기량', '많이', '딸리다'],
 ['보다'],
 ['영화', '개연', '없다', '허무', '만들다', '조디', '포스터', '이쁘다', '모습', '영화'],
 ['굳다', '굳다'],
 ['스토리', '개막', '사랑이야', '기도', '아니', '보다', '시간', '아끼다', '보다', '호구'],
 ['살리다', '아깝다', '세기', '대사'],
 ['평점',
  '너무',
  '높다',
  '전혀',
  '재미있다',
  '쓸데없이',
  '많다',
  '영화',
  '조연',
  '뒷받침',
  '중요',
  '조연',
  '내용',
  '자체',
  '전혀',
  '없다',
  '여배우',
  '별로',
  '매력',
  '없다',
  '이틀',
  '저스트',
  '고위',
  '애니',
  '스톤',
  '보다',
  '영화',
  '보다',
  '그렇다',
  '실망'],
 ['맛깔', '드라마'],
 ['시베리아', '인가', '가다', '훈련', '나오다', '작살'],
 ['이건',
  '시종일관',
  '제목',
  '야경꾼 일지',
  '지금',
  '넘어가다',
  '넘어가다',
  '군가',
  '얘기',
  '그렇다',
  '순간',
  '진짜',
  '지루함',
  '지존'],
 ['나이', '들다', '이해', '가다', '영화'],
 ['슬픔'],
 ['장면',
  '개연',
  '없다',
  '아역',
  '연기',
  '추노',
  '나오다',
  '민폐',
  '외국',
  '인줄',
  '초반',
  '그럴싸',
  '저급',
  '영화'],
 ['영화', '정말', '별루', '결말', '이상'],
 ['딱히', '재미', '없다'],
 ['송강호', '정말', '연기', '위하다', '태어나다', '인하다', '즐거움', '느끼다', '송강호', '연기', '파다'],
 ['일본', '영화', '수입', '금지', '시절', '비디오', '테이프', '돌리다', '불후의 명작', '그립다'],
 ['살인',
  '소재',
  '영화',
  '이토록',
  '재밌다',
  '살인',
  '대하다',
  '감독',
  '해석',
  '정말',
  '재치',
  '있다',
  '배우',
  '모습',
  '정말',
  '유쾌',
  '재밌다'],
 ['라파스', '신봉선', '닮다', '보다'],
 ['케이블', '그만', '재탕'],
 ['멋지다', '정말', '멋지다', '이외', '없다'],
 ['어떻다', '영화', '만들다', '의문', '당대', '최고', '영화', '지금', '보다', '결코', '떨어지다'],
 ['지금', '내다', '보다', '한심'],
 ['쓰레기', '연예인', '재기'],
 ['좋다'],
 ['많다', '감동', '드라마'],
 ['발로',
  '만들다',
  '영화',
  '지진',
  '나서다',
  '주인공',
  '넘어지다',
  '사람',
  '유유히',
  '걷다',
  '다니다',
  '있다',
  'CG',
  '연기',
  '시나리오',
  '내용',
  '정말',
  '같다'],
 ['적당히', '언제', '끝나다'],
 ['잊다', '없다', '안개', '끼다', '워터', '다리', '마스코트'],
 ['사토시',
  '감독',
  '안타깝다',
  '돌아가다',
  '가슴',
  '먹먹',
  '정말',
  '천재',
  '감독',
  '가다',
  '이제',
  '와서',
  '다시',
  '보다',
  '작품',
  '대작'],
 ['많다', '생각', '지다'],
 ['없다', '줄다'],
 ['어리다',
  '영화로',
  '알다',
  '나이',
  '들다',
  '인생',
  '뭉클',
  '영화',
  '세상',
  '살아가다',
  '갈수록',
  '오다',
  '닿다',
  '많다',
  '세상',
  '비정',
  '비정',
  '함마',
  '지다',
  '따뜻',
  '친구'],
 ['영상', '너무나', '멋지다'],
 ['비디오', '있다', '보다', '1997년', '도인', '모르다', '정도', '만들다', '긴장감', '있다'],
 [],
 ['만들다',
  '재밌다',
  '영화',
  '길다',
  '다듬다',
  '소재',
  '좋다',
  '몰입',
  '기대',
  '이상',
  '매끄럽다',
  '부분',
  '있다',
  '연기'],
 ['지나다',
  '코미디',
  '뼈대',
  '있다',
  '가문',
  '이야기',
  '섞다',
  '지루',
  '박정아',
  '비롯',
  '배우',
  '보다',
  '민망',
  '연기',
  '펼치다',
  '기억',
  '남다',
  '없다'],
 ['군더더기', '없이', '진행', '재미', '없다', '문제'],
 ['심심', '재밌다', '연기', '알다', '배우', '포스'],
 ['괜찮다'],
 ['지대', '짜증', '아빠', '보다', '앗다', '민망', '죽다'],
 ['주다'],
 ['순이', '영화'],
 ['최악', '애니메이션', '지루', '재미없다', '스토리', '진부'],
 ['좋다', '의도', '다르다', '불쾌', '표현법'],
 ['줄리아', '로버츠', '귀엽다', '연인', '5년'],
 ['신선'],
 ['예술가', '사람', '인생', '당시', '시대', '상황', '느끼다', '명작'],
 ['관객', '너무', '아쉽다', '영화', '베테랑', '류승완', '감독', '역작', '강하다', '악역'],
 ['한창', '펭귄', '남북', '거짓', '평화로', '국민', '만들다', '영화'],
 ['지금', '보다'],
 ['여자', '해서', '죽다', '없다'],
 ['성룡', '단연', '고지'],
 [],
 ['감독', '의도', '전혀', '알아차리다'],
 ['하나님', '가정', '온전히', '만들다', '진리', '이신', '분이', '만들다', '영화', '보다', '마음', '보다'],
 ['흥미진진', '피다', '헤드', '죽다', '아쉽다'],
 ['국산', '코미디', '영화', '나다', '신라', '달밤', '제일', '좋다', '푸근', '따뜻'],
 ['최악', '영화', '오기', '지루'],
 ['탄탄', '배우', '걸다'],
 ['영화', '점점', '달려가다', '몰입', '도가', '높다', '영화', '이번', '처음'],
 ['결국', '감독', '자신', '의견', '지존파', '핑계', '삼다', '지존파', '살인', '정당화', '정부', '사회'],
 ['사실',
  '여부',
  '떠나다',
  '알다',
  '아더',
  '너무',
  '덜다',
  '원탁',
  '기사',
  '실제',
  '검술',
  '최고',
  '랜스',
  '알다',
  '있다',
  '트리스탄',
  '싸우다',
  '검술',
  '마치',
  '중국',
  '검술',
  '흉내',
  '내다',
  '같다',
  '란슬롯',
  '실제',
  '너무',
  '안대',
  '하트',
  '어역',
  '미스'],
 ['대한민국', '영화', '수준', '평균', '하락', '충분', '영상물'],
 ['없다'],
 ['재밌다'],
 ['재미없다', '기대', '완전', '완전', '실망'],
 ['종착역', '없다', '인생', '대유', '트레비', '슬다', '단지', '흘러가다'],
 ['시간', '아깝다', '영화'],
 ['없다', '예쁘다', '음악', '동영상', '취미', '영화', '만들다', '끝나다', '음악', '올인', '하기'],
 ['배우', '연기', '좋다', '걸다'],
 ['학위', '위조', '성범죄', '문제', '모으다', '영화', '찍다', '그러다', '제작비', '아끼다', '패자부활전'],
 ['솔직히'],
 ['완전', '재미있다', '보다', '알맞다'],
 ['잔인', '무섭다', '멋있다'],
 ['무섭다', '기분', '나쁘다'],
 ['군더더기', '없다', '깔끔', '강하다', '메세지', '전달', '뜻밖', '좋다', '영화'],
 ['영화', '최고', '그냥', '최고', '알다'],
 ['그랜드 부다페스트 호텔', '시리즈', '같다', '캐스팅', '아깝다'],
 ['빨리', '감기', '보다', '투자비', '많이', '들다', '같다', '영화사', '망하다'],
 ['도대체',
  '재밌다',
  '건지',
  '모르다',
  '아이언맨',
  '시리즈',
  '개그',
  '뛰어넘다',
  '웃다',
  '모르다',
  '내용',
  '뜨다',
  '없다',
  '히어로',
  '놀이',
  '이렇다',
  '평점',
  '높다',
  '모르다'],
 ['끌어가다',
  '중심',
  '있다',
  '캐릭터',
  '있다',
  '알다',
  '영화',
  '살인마',
  '대적',
  '사건',
  '해결',
  '인물',
  '없다',
  '마지막',
  '탈출',
  '나서다',
  '잡히다',
  '죽이다',
  '당하다',
  '이해',
  '없다',
  '대체',
  '조달환',
  '정유미',
  '나오다'],
 ['짜다', '리얼', '쓰레기', '영화', '보다', '나다', '정말', '영화', '절대', '보다'],
 ['비록',
  '로봇',
  '점차',
  '인간',
  '감정',
  '가지다',
  '자신',
  '대하다',
  '고민',
  '결국',
  '인간',
  '죽다',
  '앤드',
  '모습',
  '보다',
  '영화',
  '최고',
  '감동',
  '선사',
  '영화'],
 ['영구', '땡칠이', '시리즈', '레전드', '영화'],
 ['초딩',
  '친척',
  '비디오',
  '빌리다',
  '보다',
  '기억',
  '나다',
  '너무',
  '재미',
  '없다',
  '나중',
  '우연히',
  '다시',
  '보니',
  '재밌다',
  '그렇다',
  '재미',
  '없다',
  '초등학교',
  '학년',
  '사촌',
  '당시',
  '최신',
  '비디오',
  '빌리다',
  '같다'],
 ['지루', '고요', '서글프다', '선속', '머물다', '깊다', '성찰', '사색'],
 ['영화', '진짜', '보다', '펑펑', '울다', '너무', '슬프다', '같다'],
 ['짧다', '내기', '박빙', '같다'],
 ['딸리다', '심은하', '눈부시다', '미모', '아름답다', '영상', '메인 주', '제가'],
 ['나오다',
  '아직',
  '풀리다',

In [199]:
Y = data['label'].values

In [200]:
tagged = []

for idx , toks in enumerate(tokenize_docs):
    if len(toks) > 0:
        tagged.append(
            TaggedDocument(words=toks, tags=[f"DOC_{idx}"])
        )
    else:
        tagged.append(
            TaggedDocument(words="", tags=[f"DOC_{idx}"])
        )

In [201]:
# tag을 추가한 문서를 이용해서 Doc2Vec 모델에 학습 데이터로 이용
model = Doc2Vec(
    documents= tagged, 
    vector_size= 500, 
    window= 5, 
    min_count = 2,   # 데이터의 개수가 작기 때문, 실제 3-5
    dm = 1,          # PV-DM 방식
    negative = 5,    # 잘못된 단어간의 배치를 사용하여 학습에 이용
    epochs= 50, 
    seed = 42
)

In [202]:
X = np.vstack(
    [model.dv[f"DOC_{idx}"] for idx in range(len(data['document']))]
)
X.shape

(5000, 500)

In [203]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    test_size=0.2, random_state=42, stratify=Y)

In [204]:
lr = LogisticRegression(max_iter=2000, random_state=42)
svc = SVC(random_state=42)

In [205]:
lr.fit(X_train, Y_train)
pred_lr = lr.predict(X_test)

In [206]:
svc.fit(X_train, Y_train)
pred_svc = svc.predict(X_test)

In [207]:
print(classification_report(Y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.73      0.75      0.74       500
           1       0.75      0.73      0.74       500

    accuracy                           0.74      1000
   macro avg       0.74      0.74      0.74      1000
weighted avg       0.74      0.74      0.74      1000

In [208]:
print(classification_report(Y_test, pred_svc))

              precision    recall  f1-score   support

           0       0.70      0.81      0.75       500
           1       0.77      0.66      0.71       500

    accuracy                           0.73      1000
   macro avg       0.74      0.73      0.73      1000
weighted avg       0.74      0.73      0.73      1000

------

## 강사님 Ver.

In [209]:
# 라이브러리 설치
# !pip install tqdm

In [210]:
# 진행 상황들을 로그에 표시해주는 라이브러리
from tqdm import tqdm

In [211]:
# 데이터 로드
df = pd.read_csv("../data/ratings_train.txt", sep='\t')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [212]:
# 150000개의 데이터 중 결측치의 개수가 5개 인것을 확인
# 결측치의 데이터가 매우 작기때문에 제거
# 제거(drop) + 결측치(na) -> dropna()
# dropna() 함수를 Sreies에서도 내장, DataFrame 내장
df2 = df.copy()
df2['document'] = df2['document'].dropna()

In [213]:
# 실수가 많은 코드들
df2['document'] = df['document'].dropna()
df2 = df['document'].dropna()

In [214]:
# 결측치를 제거
df.dropna(inplace=True)

In [215]:
# 텍스트 정규화 함수
def nomalize(text):
    # text 매개변수에 들어오는 데이터?
        # df에 있는 document 컬럼의 vlaues ->> 리뷰 데이터
    # str(text) 사용하는 이유는?
        # 리뷰의 데이터가 문자가 아닌 경우 문자형으로 변경
    text = re.sub(r"[^각-힣0-9a-zA-Z\s\.]", " ", str(text))
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [216]:
# df['document']에서 nomalize 함수를 이용
# # nomalize에 들어가는 입자를문자열이 기본
# nomalize(df['document']) 잘못된 부분
# apply() 함수 -> 데ㅇ터프레이에서 사용하는 함수
# ap() 함수를 비롯한 기능 각각의 원소들을 추출하여 어떤 작업(함수)들을 
# df.head().apply(lambda x : str(x), axis=1)
# df.head().map(lambda x : print(X))
df = df.applymap(nomalize)

C:\Users\abohv\AppData\Local\Temp\ipykernel_22468\636701083.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(nomalize)

In [217]:
# 빈 / 공백 텍스트 존쟇ㄹ 때
df.loc[
    df['document'].isin(["", " "])
]

             id document label
972     7425748              0
1840    7095375              1
2159    7070900              1
2504    7449459              0
2648     423224              1
...         ...      ...   ...
148560  7903625              0
148940  6907774              0
149364  8014701              1
149398  7432786              0
149445  7133917              0

[436 rows x 3 columns]

In [218]:
# 빈 텍스트, 공백 텓스트 -> 길이가 1이하
df = df.loc[
    df['document'].str.len() > 1
]

In [219]:
# document에서 중복된 데이터들은 제거
df = df.drop_duplicates('document')

In [220]:
# 토큰화 함수를 생성
# 특정 품사들만 선택
allow_pos = ['NNP', 'NNG', 'VV', 'VA', 'MAG', 'XR']
# 불용어
stop_word = ['하다', '되다', '이다', '것', '수','거']

# Komoram 객채를 생성
komoran  = Komoran()

def tokenize_komoran(text):
    tokens = []
    for word, pos in komoran.pos(text):
        # wrod : 단어
        # pos : 품사
        if pos in allow_pos and word not in  stop_word:
            tokens.append(word)  
    return tokens

In [221]:
df = df.head(5000)

In [222]:
# tokens화 된 리스트를 데이터프레임에 새로운 컬럼에 추가
tokenize_sentence = [tokenize_komoran(val) for val in df['document'].values]
tokenize_sentence

[['더빙', '진짜', '짜증', '나', '목소리'],
 ['포스터', '초딩', '영화', '오버', '연기'],
 [],
 ['교도소', '이야기', '솔직히', '재미', '없', '평점', '조정'],
 ['익살', '연기', '돋보이', '영화', '스파이더맨', '늙', '보이', '하', '커스틴 던스트', '너무나'],
 ['막', '걸음마', '떼', '초등학교', '학년', '용', '영화', '별', '반개', '아깝'],
 ['원작', '긴장감', '제대로', '살리'],
 ['반개',
  '아깝',
  '욕',
  '나오',
  '이응경',
  '길용우',
  '연기',
  '생활',
  '이',
  '정말',
  '발로',
  '납치',
  '감금',
  '반복',
  '반복',
  '이',
  '드라마',
  '족도',
  '없',
  '연기',
  '못하',
  '사람',
  '모이'],
 ['액션', '없', '재미', '있', '안', '영화'],
 ['왜', '평점', '낮', '꽤', '보', '헐리우드', '화려', '너무', '길들이', '있'],
 ['짱', '진짜', '짱'],
 ['볼', '때', '눈물', '나서', '죽', '향수', '자극', '허진호', '감성', '절제', '멜로', '달인'],
 ['울', '손들', '횡단보도', '건너', '때', '뛰쳐나오', '이범수', '연기', '드럽'],
 ['담백', '깔끔', '좋', '신문', '기사', '로만', '보다', '보', '자꾸', '잊어버리', '사람'],
 ['취향',
  '존중',
  '진짜',
  '극장',
  '보',
  '영화',
  '장',
  '노',
  '재',
  '노',
  '감동',
  '스토리',
  '어거지',
  '감동',
  '어거지'],
 ['매번', '긴장'],
 ['참',
  '사람',
  '웃기',
  '바스코',
  '이기',
  '락스',
  '코',
  '까',
  '고',
  '바비',
  '이기',
  '아이돌',
  '깔',
  '그냥',
  '까',
  '안달',
  '난',
  '보이'],
 ['굿바이 레닌', '표절', '이해', '왜', '뒤', '갈수록', '재미없'],
 ['이건',
  '정말',
  '깨알',
  '캐스팅',
  '질퍽',
  '산뜻',
  '내용',
  '구성',
  '잘',
  '버',
  '러',
  '진',
  '깨알',
  '드'],
 ['약탈', '위하', '변명', '착하', '절대'],
 ['심오', '뜻', '있', '그냥', '학생', '선생', '놀아나', '영화', '절대'],
 ['보', '웃', '불', '능하'],
 ['재미없',
  '지루',
  '같',
  '음식',
  '영화',
  '만찬',
  '넘',
  '만찬',
  '이야기',
  '있',
  '음식',
  '보',
  '재미',
  '있',
  '이건',
  '보',
  '없',
  '음식',
  '별로',
  '안',
  '나오',
  '핀란드',
  '풍경',
  '별로',
  '안',
  '나오'],
 ['절대', '평범', '영화', '수작', '말씀', '드리'],
 ['주제', '좋', '중반', '지루'],
 ['다', '짜르', '납득', '없', '그렇', '꼭', '그렇', '걸', '끄'],
 ['고추', '털', '하'],
 ['카밀라', '벨', '발', '연기'],
 [],
 ['센스', '있', '연출력', '탁월', '캐스팅', '90년대', '향수'],
 ['엄',
  '포스',
  '위력',
  '다시',
  '깨닫',
  '하',
  '남',
  '꽃',
  '검사',
  '연기',
  '정말',
  '좋',
  '완전',
  '명품',
  '드라마'],
 ['졸', '쓰레기', '시간', '아깝'],
 ['재밌', '별점', '왜', '이리', '낮', '은고'],
 ['라도', '기대', '죄인', '죄인'],
 ['아직', '드라마', '인생', '최고'],
 ['패션', '대하', '열정', '안나', '윈', '투어'],
 ['키이라 나이틀리', '연기', '하', '대체', '정신', '장애', '틱', '장애'],
 ['원작', '정신', '나가', '유령', '재미있'],
 ['포스터', '있', '보이', '관객'],
 ['영화', '왜', '이렇', '받', '모르'],
 ['단순', '은은', '매력', '영화'],
 ['다',
  '알바',
  '내용',
  '없',
  '무섭',
  '거도',
  '없',
  '웃기',
  '거도',
  '없',
  '완전',
  '별',
  '싱겁',
  '영화',
  '시간',
  '넘',
  '아깝',
  '완전',
  '낚이'],
 ['오', '서리', '한', '굶주리'],
 ['정말', '맘', '들', '보', '보', '방법', '없'],
 ['윤제문',
  '멋지',
  '배우',
  '발견',
  '되',
  '소소',
  '일탈',
  '잔잔',
  '미소',
  '머금',
  '음악',
  '조금',
  '아쉽',
  '평점',
  '올리'],
 ['평점', '속지', '마시', '길', '시간', '낭비', '돈', '낭비'],
 ['리얼리티',
  '뛰어나',
  '하',
  '크',
  '공감',
  '안',
  '가',
  '이민기',
  '캐릭터',
  '정신의학',
  '분노',
  '조절',
  '장애',
  '초기',
  '증상',
  '일',
  '툭하면',
  '사람',
  '패',
  '욕',
  '물건',
  '파손',
  '조금',
  '오바',
  '극',
  '초반',
  '신선',
  '면',
  '갈수록',
  '이민기',
  '정신',
  '상태',
  '공감',
  '불'],
 ['마이너스', '왜', '없', '보', '영화', '수준', '딱', '알', '북한', '만들', '돈', '대'],
 ['나', '영화', '사랑합니다'],
 ['데',
  '리스',
  '타르',
  '르',
  '용의',
  '주인',
  '되',
  '누',
  '이랑',
  '근친상간',
  '하',
  '다니',
  '소설',
  '속',
  '제일',
  '멋지',
  '자이',
  '메',
  '라',
  '니스',
  '드라마',
  '속',
  '드래곤',
  '용',
  '제일',
  '멋지',
  '웃음',
  '감독',
  '토르',
  '다크 월드',
  '잡수',
  '기본',
  '선방',
  '하'],
 ['영화',
  '사람',
  '영혼',
  '어루만지',
  '있',
  '거치',
  '세상사',
  '잠시',
  '잊',
  '동화',
  '같',
  '영화',
  '행복'],
 ['르', '게이', '작', '고추', '매운맛', '보이', '콩', '진호', '간다'],
 ['이렇', '보', '드라마', '있', '감동', '자체'],
 ['난', '꼬마', '애', '원한', '깊', '하', '그냥', '혼자', '나대', '걸', '어쩌'],
 ['재미있'],
 ['좋'],
 ['최고'],
 ['너무',
  '충격',
  '기분',
  '완전히',
  '푹',
  '꺼지',
  '하',
  '느낌',
  '활력',
  '없',
  '너무나',
  '무겁',
  '지독',
  '차갑',
  '자비',
  '그저',
  '일본인',
  '상상력',
  '정말',
  '대단',
  '같',
  '생각',
  '들'],
 ['심심', '영화'],
 ['백봉기', '언제나', '오'],
 ['보', '그대로', '들어맞', '예측', '카리스마', '없', '악역'],
 ['불알', '나오', '당황', '아무튼', '영화', '중간', '끝나', '느낌'],
 ['평범', '함속', '녹', '아든', '평범', '일상', '조금', '밋밋'],
 ['보',
  '계속',
  '보',
  '전개도',
  '느리',
  '주인공',
  '은희',
  '컷',
  '나오',
  '소극',
  '모습',
  '짜증',
  '맨날',
  '언제',
  '끝나',
  '기대',
  '하',
  '전개',
  '좀',
  '빨리빨리'],
 ['사랑'],
 ['많',
  '사람',
  '다',
  '큐',
  '보',
  '우리나라',
  '슬프',
  '현대사',
  '단면',
  '대하',
  '깊이',
  '생각',
  '사죄',
  '바로',
  '잡기',
  '위하',
  '노력',
  '말',
  '듣',
  '보도',
  '연맹',
  '민간인',
  '학살',
  '이정',
  '이건',
  '명백',
  '살인',
  '살인자',
  '다',
  '있'],
 ['예전',
  '작품',
  '캐릭터',
  '에피소드',
  '재탕',
  '삼탕',
  '사골',
  '우려',
  '먹',
  '내용',
  '산',
  '시청률',
  '아예',
  '안',
  '나오',
  '이제',
  '중반'],
 ['김남길', '연기력', '초반', '몰입', '불구', '지루', '손예진'],
 ['재밌', '비슷', '영화', '안보', '신', '재미있'],
 ['노래', '실력', '뽑', '맞', '박시환', '면', '진짜', '망신'],
 ['일본', '영화', '다', '유치'],
 ['이틀',
  '다',
  '보',
  '재밌',
  '안',
  '물건',
  '넣',
  '조작',
  '하',
  '안',
  '열리',
  '집',
  '안',
  '활짝',
  '열리',
  '들어가',
  '문자',
  '조작',
  '비번',
  '안',
  '걸리',
  '억지',
  '내용',
  '자체',
  '좋'],
 ['졸', '작'],
 ['달팽이', '빠르', '더', '재밌'],
 ['어설프', '전개', '어이없', '결말'],
 ['부패', '로마노프 왕조', '기리', '같', '영화', '온몸', '항거', '러시아', '민중', '그저', '폭', '돌'],
 ['내용', '전개', '무난', '편이', '잘', '보'],
 ['매우', '실망'],
 ['한국',
  '영화',
  '흥행',
  '코드',
  '갈등',
  '갈등',
  '계',
  '에',
  '속',
  '갈등',
  '화해',
  '감동',
  '평점',
  '남발',
  '흥행',
  '뻔하'],
 ['아햏햏', '아햏햏', '아햏햏'],
 ['시작', '3분', '나오', '리플릿', '사진', '보', '불안'],
 ['단연', '최고', '하'],
 ['감독', '영화', '만들', '관객', '말', '모르', '엉망진창', '개진', '창'],
 ['이건', '우뢰', '매'],
 ['정말', '쓰레기', '영화'],
 ['진정', '위대', '영화', '최고'],
 ['별루'],
 ['내일', '기대'],
 ['조미', '막', '문', '좋아하'],
 ['진짜', '골', '까', '눈', '부라리', '때', '쓰러지'],
 ['성룡', '영화', '최', '악인'],
 ['골', '때리', '걸스데이', '이혜리', '잘', '되'],
 ['서기', '이쁘'],
 ['완전', '재밌', '백인', '공주', '귀여움'],
 ['인상', '영화'],
 ['세', '레', '스티', '완전', '강', '추', '정말', '재밌'],
 ['재미있', '영화'],
 ['클라라', '볼라', '고', '화신', '본'],
 ['진짜', '보', '너무', '슬프', '영화'],
 ['설정', '재밌', '새롭', '에피소드', '메인', '스토리', '차차', '나오', '재밌'],
 ['신카이 마코토', '작화', '미', '유', '카나', '연기', '잘', '더', '대박', '이'],
 ['재미없', '진심', '캐스팅'],
 ['잔잔', '생각', '보', '영화인', '같'],
 ['감독', '고은님', '쓰', '영화', '안', '보'],
 ['무섭', '스토리'],
 ['영화', '속', '억지', '노골적', '술', '광고', '좀', '은은', '센스', '있', '하', '어떻'],
 ['킬링타임'],
 ['크리스마스', '떠오르', '영화'],
 ['재미있', '보', '매력', '행복'],
 ['음악', '완전히', '빠지', '보', '영화', '쪼', '산만', '하'],
 ['태어나', '처음', '영화', '중간', '나오', '불륜', '로맨스', '냐'],
 ['왕', '짜증', '아주', '전개', '짬뽕', '믹스', '음향', '무섭', '하'],
 ['솔직히', '나', '별루', '덜', '시간', '낭비', '느낌'],
 ['대박'],
 ['시청률', '기준', '되', '패널', '구', '거지', '명작', '드라마', '다', '망치', '다', '서운'],
 ['내용', '이상해'],
 ['몬스터 주식회사', '3D', '재밌', '보'],
 ['내용', '전개', '너무나', '느리'],
 ['소재', '흥미', '끌', '이야기', '전개', '투박', '몰입', '안'],
 ['절대', '보지', '마라', '쓰레기', '영화'],
 ['중국인',
  '특유',
  '과장',
  '허풍',
  '있',
  '보이',
  '안간힘',
  '쓰',
  '노력',
  '상하',
  '고증',
  '현실감',
  '떨어지',
  '설정',
  '거북',
  '도대체',
  '왜',
  '이렇',
  '스스로',
  '대포',
  '장하'],
 ['그냥', '불법체류', '때려잡', '영화', '좋', '텐', '우상', '만들', '미국', '따뜻', '설정', '이건'],
 ['2년', '삶', '속', '주인공', '생애', '전부', '드러나'],
 ['별점'],
 ['별로', '다'],
 ['보', '꽤', '지나', '후', '남기', '재미있'],
 ['아니', '이', '왜', '일'],
 ['지나', '다시', '보', '되', '영화', '다시', '보', '순수', '사랑', '감동', '쇼', '펜', '연기'],
 ['올레',
  '공짜',
  '있',
  '보',
  '허',
  '스토리',
  '문제',
  '연기자',
  '전혀',
  '배역',
  '이랑',
  '어울리',
  '상대',
  '배우',
  '다',
  '따로',
  '같',
  '이건',
  '연기자',
  '문제',
  '있',
  '보',
  '진심',
  '완전',
  '별로',
  '라미란',
  '아들',
  '젤',
  '볼',
  '하'],
 ['너무', '욕심', '많', '영화', '제대로', '보이'],
 ['빵점'],
 ['베', '말', '아주', '잘', '쓰'],
 ['아주', '모자', '라진'],
 ['영화', '도둑들', '뫼비우스', '하', '같', '나라', '만들', '믿'],
 ['온몸', '찌릿', '짜릿', '용기'],
 ['정말', '재미있', '교훈', '영화'],
 ['당시', '상황', '주제', '주입식', '긴장감', '있', '재밌', '전하', '작품'],
 ['케이블', '그만', '나오'],
 ['다르', '냐', '리', '차이밍량', '안', '섞이', '짬뽕', '그릇', '담기'],
 ['여군', '재', '없', '뭐', '건지', '재', '없', '다', '재', '없', '질리', '다이'],
 ['좋'],
 ['한석규', '김혜수', '연기', '돋보이', '영화', '모르', '많이', '어설프', '영화'],
 ['솔직히',
  '에볼라바이러스',
  '떠들석',
  '보',
  '되',
  '영화',
  '작품',
  '면',
  '여',
  '전',
  '영화',
  '믿',
  '힘들',
  '정도',
  '정말',
  '잘',
  '만들',
  '마지막',
  '후반부',
  '살짝',
  '아쉽',
  '하',
  '이정',
  '도면',
  '수작',
  '시간',
  '아깝',
  '영화'],
 ['보', '만해'],
 ['재미있', '허풍', '떨', '마'],
 ['용', '진짜', '짱', '짱', '매'],
 ['영화',
  '이제서야',
  '감히',
  '인생',
  '최고',
  '영화',
  '하나로',
  '꼽',
  '있',
  '작품',
  '어떻',
  '살',
  '위하',
  '고민',
  '더',
  '하',
  '되',
  '시간',
  '모건 프리먼',
  '나이',
  '들',
  '여전히',
  '섹시'],
 ['작',
  '별로',
  '다',
  '내용',
  '이',
  '진짜',
  '맨날',
  '그냥',
  '기대',
  '재방송',
  '혹시나',
  '답',
  '없',
  '진짜'],
 ['명작', '명작', '있', '보', '보', '여운', '남', '영화'],
 ['진짜',
  '조금',
  '더',
  '손',
  '좀',
  '보',
  '왜',
  '하',
  '상업',
  '영화',
  '못하',
  '만들',
  '아쉽',
  '충분히',
  '재미있',
  '개인',
  '조금',
  '더',
  '잔인',
  '더',
  '자극',
  '노출',
  '화끈',
  '하',
  '어떻',
  '하',
  '국산',
  '영화',
  '많이',
  '아끼',
  '보이'],
 ['그만', '좀', '끌', '이제', '끝내', '지겹', '지겹'],
 ['드니', '연기', '일품', '맥스', '샘', '죽이', '하'],
 ['괜찮', '작품'],
 ['너무', '좋', '영화'],
 ['정말', '실망'],
 ['배우',
  '지',
  '안',
  '뜨',
  '영화',
  '찍',
  '껀',
  '왜',
  '안',
  '뜨',
  '진짜',
  '모르',
  '면상',
  '딱',
  '보',
  '알',
  '왜',
  '자신',
  '모르'],
 ['어린이', '좋아하', '어리', '동심', '멀리', '뜨', '낫'],
 ['무술', '인', '왜', '총', '들'],
 [],
 ['크리스토퍼', '왈츠', '타란티노', '조합'],
 ['한국', '에선', '유명한', '외국', '상상', '초월', '유명', '영화'],
 ['오랜만'],
 ['종',
  '방',
  '아쉽',
  '오늘',
  '막',
  '방도',
  '잘',
  '보',
  '방송',
  '대본',
  '꽤',
  '완성도',
  '있',
  '느낌',
  '받',
  '요즘',
  '드라마',
  '막장',
  '지치',
  '향',
  '정말',
  '바른',
  '드라마',
  '악역',
  '그리',
  '심하',
  '어이없',
  '화이팅'],
 ['평점',
  '조절',
  '위원회',
  '나오',
  '웃음',
  '김혜선',
  '내일이 오면',
  '의',
  '김',
  '순정',
  '순정',
  '역할',
  '정도',
  '잘',
  '해내',
  '정말',
  '의외',
  '연기',
  '20년',
  '사람',
  '요즘',
  '사극',
  '벌어지',
  '있',
  '대하',
  '연기',
  '논란',
  '왠지',
  '코미디',
  '의하',
  '장면',
  '같',
  '웃음'],
 ['영화', '끝나', '때', '멍하', '다', '보', '한마디', '나오', '같'],
 ['공유', '존', '잘'],
 ['상쾌', '발랄', '영화', '말', '끌', '성', '소재', '유쾌', '해설'],
 ['소파', '죽', '치', '앉', '지키', '보', '이유', '없', '작품'],
 ['로큰롤'],
 ['주되',
  '타겟',
  '어린이',
  '일반',
  '논리',
  '통하',
  '알',
  '게임',
  '흥미',
  '요원',
  '주인공',
  '너무',
  '능력',
  '별로',
  '재미없',
  '배경',
  '거슬리'],
 ['뮤지컬 영화',
  '사운드',
  '녹음',
  '엉망',
  '남',
  '주',
  '춤',
  '못',
  '추',
  '내용',
  '뻔하',
  '주인공',
  '목소리',
  '너무',
  '안',
  '어울리',
  '어제',
  '뛰',
  '참',
  '진심',
  '말리',
  '영국',
  '예산',
  '영화',
  '뮤지컬',
  '영화',
  '맘마미아',
  '10',
  '안'],
 ['어리', '나이', '보', '꽤', '좋아하', '로맨틱', '코미디'],
 ['게이', '물', '인줄', '모르', '보'],
 ['알바', '끄', '절'],
 ['영화', '왜', '받', '보', '알', '이', '영화', '배우', '스텝', '감독', '꼭두각시'],
 ['최악'],
 ['정말', '아름답', '영화', '이'],
 ['자극', '익숙', '현대인', '보', '눈', '떼', '힘들', '연출력'],
 ['뻑', '뻑', '잘', '읽', '당하'],
 ['정말',
  '짜증',
  '극치',
  '보이',
  '영화',
  '굉장히',
  '느낌',
  '뚱뚱',
  '못생기',
  '남자',
  '애',
  '발',
  '연기',
  '시종일관',
  '보',
  '고역',
  '흘러나오',
  '잔잔',
  '클래식',
  '음악',
  '조차',
  '듣',
  '싫',
  '짜증',
  '날',
  '정도',
  '상당히',
  '싫',
  '영화'],
 ['감동', '감동', '정말', '최고'],
 ['별점',
  '아깝',
  '얼마나',
  '내용',
  '진부',
  '욕',
  '밖',
  '안',
  '나오',
  '재밌',
  '하',
  '사람',
  '초딩',
  '죄송',
  '너무',
  '화',
  '나서',
  '보',
  '없',
  '보',
  '마',
  '그냥',
  '티',
  '비판',
  '짜',
  '집기',
  '같'],
 ['왜', '하', '짜증', '안', '내'],
 ['돼지', '피', '먹', '닭목', '따', '장면', '에선', '무당', '하'],
 [],
 ['유치', '지루', '잠'],
 ['판타지'],
 ['윤종신',
  '복귀',
  '좋',
  '이하늘',
  '도대체',
  '왜',
  '뽑히',
  '알',
  '없',
  '참',
  '실력',
  '따지',
  '전',
  '심사',
  '위원',
  '인격',
  '실력',
  '쌓',
  '오시',
  '길',
  '어',
  '허',
  '그만',
  '좀',
  '하'],
 ['광장', '작품', '옛날', '보고 싶다'],
 ['생', '최고', '영화'],
 ['어리',
  '시절',
  '너무',
  '무섭',
  '재미있',
  '보',
  '추억',
  '판타지',
  '영화',
  '절대',
  '나쁘',
  '짓',
  '금물',
  '지옥',
  '요'],
 ['기존', '멜로', '영화', '형식', '탈피', '하', '감정', '절제', '지나치', '너무', '담백', '영화'],
 ['나', '사랑비', '서주', '쏙', '빠지', '쏙', '나', '절대', '잊', '후회', '도안', '할거'],
 ['이영화', '보', '교훈', '남은', '인생', '화려', '말', '안', '나오'],
 ['추억', '젖', '좋', '생각', '없이', '보', '추천'],
 ['단순', '싸이코', '물', '벗어나'],
 ['이', '만들', '예전', '만들', '다시', '개봉', '한', '너무', '허', '접하'],
 ['넘', '사랑', '영화', '보고', '연잇', '보', '넘', '귀여워'],
 ['청춘 영화',
  '있',
  '감성',
  '넘치',
  '순간',
  '지나',
  '면',
  '다시',
  '돌아오',
  '테',
  '순간',
  '무한',
  '젊음',
  '있',
  '감성'],
 ['건담', '시리즈', '아직', '최고봉'],
 ['개코', '요즘', '갈수록', '코너', '달', '재', '웃음', '이안', '나'],
 ['사다코', '한', '서리', '우물', '펀치', '감동'],
 ['후세',
  '사랑',
  '되',
  '결정',
  '계기',
  '시간',
  '표현',
  '생명',
  '빼앗',
  '이유',
  '시노',
  '출현',
  '연극',
  '으',
  '로',
  '더',
  '알리',
  '하',
  '생각',
  '시노',
  '얼마나',
  '시랑',
  '하',
  '노력',
  '더',
  '보이',
  '좋'],
 ['새벽',
  '시간',
  '하',
  '일본',
  '영화',
  '전부',
  '개',
  '졸',
  '작',
  '일본',
  '영화',
  '원래',
  '다',
  '이러'],
 ['강수연', '있', '최정원', '신음', '신'],
 ['정말', '김혜성', '너무', '예쁘', '이현진', '웃', '정말'],
 ['발', '쓰'],
 ['화려', '여', '정', '이인상', '깊', '배두나', '연기', '정말', '잘'],
 ['10대', '위하', '성적', '호기심', '영화'],
 ['감동', '영화'],
 ['이건', '말', '필요', '없', '그냥', '닥치', '보'],
 ['각기', '사람', '재밌', '멋지', '사랑', '영화'],
 ['미국', '드라마', '파워', '정말', '알', '수없', '미묘', '사로잡', '최고'],
 ['너무너무', '훈훈'],
 ['응답하라', '은지원', '원도', '스스로', '욕'],
 ['너무', '웃기', '배꼽', '빠지', '컴', '영화', '있'],
 ['구성', '상당히', '부실', '영화', '네이버', '평점', '믿', '없'],
 ['장', '끌', '로드', '몰락', '오우삼', '헐리우드', '작품', '장', '재미없', '졸', '작'],
 ['영웅본색', '연출', '인지', '현실', '제로', '영화'],
 ['작',
  '하나에',
  '설레',
  '학창',
  '시절',
  '그때',
  '느낌',
  '다시',
  '느끼',
  '시간',
  '장면',
  '대사',
  '배경',
  '음악',
  '없',
  '드라마'],
 ['진심', '재미', '없', '너무', '평점', '높', '화나'],
 ['더럽', '재미없', '형태', '오', '닿', '허무', '완벽히', '지루', '영화', '영양', '없', '영화'],
 ['이승기', '정말', '연기', '잘', '조연', '연기', '정말', '잘'],
 ['현실', '꿈', '꿈', '현실'],
 ['오늘', '현충일', '특집', '프로', '보', '되', '매우', '훌륭', '작품'],
 ['판', '의미', '동급'],
 ['제대', '보', '더', '재밌'],
 ['영화',
  '보',
  '마음',
  '휴',
  '다녀오',
  '느낌',
  '소',
  '박',
  '하지',
  '잔잔',
  '지루',
  '다시',
  '보',
  '영화',
  '햇살',
  '득',
  '이',
  '부엌',
  '요리',
  '인상'],
 ['코믹', '좋', '짜임새', '너무', '허술'],
 ['그때',
  '당시',
  '나라',
  '판타지',
  '로맨스',
  '없',
  '아직',
  '신현준',
  '황',
  '장군',
  '연기',
  '괜찮',
  '한석규',
  '전성시대',
  '열리',
  '영화',
  '이때',
  '한석규',
  '뿅',
  '가'],
 ['일단', '재생', '괴물', '같', '서스펜스', '귀신', '같', '흡입', '력'],
 ['진짜',
  '댓글',
  '한번쯤',
  '볼',
  '영화인',
  '같',
  '기',
  '죽기',
  '직전',
  '소원',
  '들어주',
  '보',
  '죽기',
  '직전',
  '막',
  '살',
  '인',
  '같',
  '감동',
  '없',
  '진짜',
  '란',
  '영화',
  '발톱',
  '때',
  '못',
  '따르',
  '늘',
  '쓰레기',
  '영화',
  '와',
  '존',
  '실망'],
 ['시간',
  '좀',
  '밝',
  '긍정',
  '드라마',
  '보',
  '보기',
  '보',
  '오버',
  '연기',
  '거슬리',
  '연기',
  '인',
  '게',
  '너무',
  '표',
  '요',
  '홍혜정',
  '역',
  '이그',
  '마도',
  '후련',
  '기도',
  '고시원',
  '나머지',
  '들',
  '답답',
  '내',
  '월요일',
  '해피',
  '한',
  '보'],
 ['정치인', '모순', '정치범', '모순'],
 ['어떻', '상상', '대단'],
 ['좀', '어렵', '하', '전쟁', '대하', '묘사', '잘', '모르'],
 ['일본', '극장판', '만들', '우리나라', '에선', '개봉', '하니', '이건', '좀'],
 ['개그콘서트', '보', '전화', '끊', '개그', '콘서트', '없애'],
 ['한물', '동서양', '배우', '싸움판'],
 ['푸', '하', '하', '하', '기대', '안'],
 ['세계', '최초', '반공', '애니매이션', '역사'],
 ['감각', '시각', '바라보', '색다르', '느낌', '사랑', '문학'],
 ['엄마', '무고', '딸', '감옥살이', '시키', '시키', '이해', '안'],
 ['이영화', '제발', '책', '을', '보세', '감독', '미치', '이', '만들', '화', '날', '정도'],
 ['신나', '흑인', '음악', '아이스 큐브', '남', '없'],
 ['드럽', '재미없', '시간', '돈', '시간', '어쩌'],
 ['그저', '한마디', '알리'],
 ['진짜', '생생', '느끼'],
 ['재밌', '평점', '이상', '정도', '낮'],
 ['옥소리', '프로필', '사진', '남기', '가', '완전', '대박', '진짜', '아우', '짜증'],
 ['드라마', '너무'],
 ['아', '진짜', '너무', '좋', '짱', '짱'],
 ['연기', '굿'],
 ['영화', '다시', '안', '나오', '그때', '시절', '잘', '나타내', '같'],
 ['중간', '정도', '보', '꽤', '대단'],
 ['콩', '까', '제맛', '콩', '까', '제맛'],
 ['소설', '재미없'],
 ['액션', '영화', '범죄', '느와르', '영화', '범죄', '느와르', '영화', '실패작'],
 ['알', '수없', '매력', '빠지', '영화'],
 ['모녀',
  '토막',
  '살해',
  '살인자',
  '성애',
  '말이',
  '감동',
  '받',
  '사람',
  '본인',
  '피해자',
  '감동',
  '받',
  '하',
  '진심',
  '묻'],
 ['재밌', '평점', '왜', '이렇', '구리지'],
 ['보', '눈', '아깝', '진짜', '놓', '진짜', '기', '명작'],
 ['필름', '값', '아깝', '재미', '더럽', '없', '점', '수준', '매미'],
 ['보'],
 ['영화', '재미있'],
 ['남주인공',
  '연기력',
  '안',
  '습',
  '혀',
  '짧',
  '소리',
  '듣',
  '너무',
  '힘들',
  '매니저',
  '역활',
  '분이',
  '남주인공',
  '좋',
  '생각',
  '들',
  '정도',
  '영화',
  '자체',
  '적당히',
  '보',
  '하'],
 ['딱', '액션', '스릴러', '액션', '스릴', '없'],
 ['완전', '스토리', '엉망', '완전', '추'],
 ['영화', '전달', '모르', '오', '글', '거리'],
 ['좋', '영화'],
 ['더빙', '이상', '할머니', '월래', '익숙'],
 ['이', '나오'],
 ['게', '씩', '다', '부족', '씩'],
 ['정말', '말', '그대로', '쇼', '하', '영화'],
 ['전', '보', '기억', '진개', '천카이거', '감독', '이름', '기억', '두'],
 ['정은지', '언니', '연기', '잘', '노래', '잘', '부르', '마지막', '웃', '즐겁', '보', '트로트의 연인'],
 ['이'],
 ['망하'],
 ['아이', '시선', '보', '전쟁', '보', '내내', '먹먹'],
 ['사람',
  '재미없',
  '하',
  '레알',
  '기대',
  '안',
  '생각',
  '보',
  '여자',
  '애',
  '복순이',
  '다투',
  '장면',
  '굳이',
  '없',
  '되',
  '생각',
  '몰입',
  '겁나',
  '없애',
  '어색',
  '보이'],
 ['설정', '연속극', '같', '느낌', '들', '배우', '연기', '뛰어나'],
 ['여주인공', '인터뷰', '때', '지루', '죽', '알', '그냥저냥', '킬링타임', '스릴러'],
 ['미',
  '박스',
  '오피스',
  '그냥',
  '몰아주',
  '하',
  '어떻',
  '영화',
  '하',
  '옛날',
  '90년대',
  '우뢰',
  '매',
  '수준',
  '물',
  '폭탄',
  '싸움',
  '손',
  '빔',
  '손',
  '물',
  '폭탄',
  '다르'],
 ['감독', '여자', '다', '보니', '기량', '많이', '딸리'],
 ['보'],
 ['영화', '개연', '없', '허무', '만들', '조디', '포스터', '이쁘', '모습', '남', '영화'],
 ['굳', '굳'],
 ['스토리',
  '말',
  '안',
  '개막',
  '장',
  '사랑이야',
  '기도',
  '아니',
  '예',
  '보',
  '시간',
  '돈',
  '아끼',
  '예',
  '휴',
  '보',
  '호구'],
 ['살리', '쌀', '아깝', '세기', '대사'],
 ['평점',
  '너무',
  '높',
  '전혀',
  '재미있',
  '쓸데없이',
  '말',
  '많',
  '류',
  '영화',
  '조연',
  '뒷받침',
  '중요',
  '조연',
  '내용',
  '자체',
  '전혀',
  '없',
  '여배우',
  '별로',
  '매력',
  '없',
  '이틀',
  '전',
  '저스트',
  '고위',
  '드',
  '잇',
  '애니',
  '스톤',
  '보',
  '영화',
  '보',
  '실망'],
 ['맛깔', '드라마'],
 ['시베리아', '서', '훈련', '때', '나오', '작살'],
 ['이건',
  '시종일관',
  '왜',
  '제목',
  '야경꾼 일지',
  '냐',
  '지금',
  '넘',
  '늘',
  '달',
  '넘',
  '앞',
  '얘기',
  '하',
  '더',
  '그렇',
  '순간',
  '훅',
  '진짜',
  '지루함',
  '지존'],
 ['나이', '들', '이해', '늘', '영화'],
 ['슬픔'],
 ['장면',
  '개연',
  '없',
  '아역',
  '연기',
  '추노',
  '나오',
  '민폐',
  '언',
  '외국',
  '판',
  '인줄',
  '초반',
  '그럴싸',
  '저급',
  '영화'],
 ['영화', '정말', '별루', '예', '결말', '이상'],
 ['딱히', '재미', '없'],
 ['송강호', '정말', '연기', '하', '위하', '태어나', '인하', '즐거움', '느끼', '송강호', '연기', '파다'],
 ['일본', '영화', '수입', '금지', '시절', '비디오', '테이프', '돌리', '불후의 명작', '그립'],
 ['살인',
  '소재',
  '영화',
  '이토록',
  '재밌',
  '살인',
  '대하',
  '감독',
  '해석',
  '정말',
  '재치',
  '있',
  '배우',
  '여',
  '전',
  '모습',
  '정말',
  '유쾌',
  '재밌'],
 ['누', '미', '라파스', '신봉선', '닮', '안', '보'],
 ['케이블', '그만', '좀', '재탕'],
 ['멋지', '정말', '멋지', '말', '이외', '하', '말', '없'],
 ['어떻', '영화', '만들', '의문', '당대', '최고', '영화', '지금', '보', '결코', '떨어지'],
 ['지금', '티', '비', '돈', '내', '보', '한심'],
 ['쓰레기', '연예인', '재기', '장'],
 ['굿', '좋'],
 ['많', '감동', '드라마'],
 ['발로',
  '만들',
  '영화',
  '지진',
  '나서',
  '주인공',
  '넘어지',
  '뒤',
  '사람',
  '유유히',
  '걷',
  '다니',
  '있',
  '발',
  'CG',
  '발',
  '연기',
  '발',
  '시나리오',
  '내용',
  '정말',
  '같'],
 ['적당히', '하', '언제', '끝나'],
 ['잊', '없', '안개', '끼', '워터', '다리', '마스코트'],
 ['곤',
  '사토시',
  '감독',
  '안타깝',
  '돌',
  '시',
  '먹먹',
  '정말',
  '천재',
  '감독',
  '암',
  '시',
  '이제',
  '와서',
  '다시',
  '보',
  '작품',
  '대작'],
 ['많', '생각', '하', '되', '예', '뼈', '지', '맘', '과', '독'],
 ['없', '줄'],
 ['어리',
  '때',
  '영화로',
  '알',
  '나이',
  '들',
  '이',
  '인생',
  '하',
  '뭉클',
  '영화',
  '세상',
  '살',
  '면',
  '갈수록',
  '오',
  '닿',
  '많',
  '세상',
  '비정',
  '비정',
  '함마',
  '지',
  '따뜻',
  '친구'],
 ['영상', '너무나', '멋지'],
 ['비디오', '있', '보', '1997년', '도인', '줄', '모르', '정도', '잘', '만들', '긴장감', '있'],
 ['처'],
 ['만들',
  '재밌',
  '영화',
  '길',
  '좀',
  '다듬',
  '소재',
  '좋',
  '몰입',
  '감',
  '기대',
  '이상',
  '매끄럽',
  '부분',
  '있',
  '연기',
  '다',
  '잘'],
 ['철',
  '지나',
  '코미디',
  '뼈대',
  '있',
  '문',
  '이야기',
  '섞',
  '다',
  '지루',
  '박정아',
  '비롯',
  '배우',
  '보',
  '민망',
  '연기',
  '펼치',
  '기억',
  '남',
  '없'],
 ['군더더기', '없이', '잘', '진행', '재미', '없', '문제'],
 ['심심', '재밌', '탑', '연기', '알', '배우', '포스', '잘'],
 ['다', '미', '괜찮'],
 ['지대', '짜증', '아빠', '보', '앗', '민망', '죽'],
 ['못', '주'],
 ['빠', '순이', '영화'],
 ['최악', '애니메이션', '지루', '재미없', '스토리', '진부'],
 ['좋', '의도', '다르', '불쾌', '표현법'],
 ['줄리아', '로버츠', '귀엽', '연인', '5년', '전'],
 ['신선'],
 ['예술', '사람', '인생', '당시', '시대', '상황', '느끼', '명작'],
 ['관객', '너무', '아쉽', '영화', '베테랑', '더', '류승완', '감독', '역작', '더', '강하', '악역'],
 ['한창', '핵', '펭귄', '남북', '거짓', '평화로', '전', '국민', '속', '때', '만들', '영화'],
 ['지금', '티', '비', '못', '보'],
 ['여자', '애', '못', '해서', '죽', '답', '없'],
 ['성룡', '단연', '최', '고지'],
 ['안', '습'],
 ['감독', '의도', '전혀', '알아차리'],
 ['하나님',
  '정',
  '을',
  '온전히',
  '만들',
  '진리',
  '이신',
  '분이',
  '만들',
  '영화',
  '눈',
  '보',
  '마음',
  '보'],
 ['흥미진진', '피', '헤드', '죽', '좀', '아쉽'],
 ['국산', '코미디', '영화', '나', '신라', '달밤', '제일', '좋', '뭐', '푸근', '따뜻'],

In [223]:
df['document_tokenize'] = tokenize_sentence

In [224]:
df.head()

,id,document,label,document_tokenize
0,9976970,아 더빙.. 진짜 짜증나네요 목소리,0,"[더빙, 진짜, 짜증, 나, 목소리]"
1,3819312,흠...포스터보고 초딩영화줄....오버연기조차 볍지 않구나,1,"[포스터, 초딩, 영화, 오버, 연기]"
2,10265843,너무재밓었다그래서보는것을추천한다,0,[]
3,9045019,교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정,0,"[교도소, 이야기, 솔직히, 재미, 없, 평점, 조정]"
4,6483659,사이몬페그의 익살스런 연기 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 던...,1,"[익살, 연기, 돋보이, 영화, 스파이더맨, 늙, 보이, 하, 커스틴 던스트, 너무나]"

In [231]:
# 토큰화된 문서에 Tag를 부착
def tagged_docs(tokenize_data):
    tagged = []
    for d_id, toks in enumerate(tokenize_data):
        # toks의 길이가 0이라면 -> 학습에서 의미없는 문장
        if len(toks) == 0:
            continue
        tagged.append(
            TaggedDocument(
                words=toks, tags=[f"DOC_{d_id}"]
            )
        )
    return tagged

In [232]:
# 데이터셋
train_df, test_df = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df['label']
)

In [233]:
# Doc2Vec에서 사용할 데이터는 train_df의 document_token 컬럼의 데이터를 이용한다
tagged_train = tagged_docs(train_df['document_tokenize'].values)

In [238]:
len(tagged_train)

3927

In [234]:
# Dov2Vec 객체를 생성하여 학습
model2 = Doc2Vec(
    documents=tagged_train,
    vector_size=200,
    window=5,
    dm=1,
    min_count=2,
    negative=5,
    seed=42,
    epochs=50
)

In [235]:
# 단어 사전의 개수 확인 -> 단어별 임베딩 벡터wv
print("단어 사전의 개수 : ", len(model2.wv))

단어 사전의 개수 :  2785

In [237]:
len(model2.dv)

3927

In [239]:
# 새로운 문장을 model에 infer_vector 함수를 이용하여 임베딩
def infer_vector(model, norm_texts, epochs=50, ):
    # norm_texts : 정규화 처리가 끝난 문서들
    # model : 임베딩 모델
    vecs = []
    
    for text in norm_texts:
        # text : norm_texts의 각 원소들의 대입
        tokens = tokenize_komoran(text)
        # 토큰화된 데이터가 길이가 0인 경우
        if len(tokens) == 0:
            # 비어있는 토큰 데이터는 영벡터 / 평균 벡터로 대체 가능
            # 영벡터로 출력
            vecs.append(np.zeros(model.vector_size, dtype=np.float32))
        else:
            vec = model.infer_vector(tokens, epochs=epochs)
            vecs.append(vec)
    return np.vstack(vecs)

In [242]:
x_train = infer_vector(model2, train_df['document'].values)
y_train = train_df['label'].values

x_test = infer_vector(model2, test_df['document'].values)
y_test = test_df['label'].values

In [243]:
x_train.shape

(4000, 200)

In [245]:
# 로지스틱회귀 모델과 선형 서포트벡터 분류 모델에 학습하고 정확도 체크하는 함수
def eval_clf(clf, x_tr, y_tr, x_te, y_te, model_name):
    # 모델에 학습
    clf.fit(x_tr, y_tr)
    # 모델을 통한 예측
    pred = clf.predict(x_te)
    # 정확도
    acc = accuracy_score(y_te, pred)
    print(f"{model_name}모델의 정확도는 : ", round(acc, 4))
    # class report
    cls_report = classification_report(y_te,pred)
    print(f"{model_name}모델의 report : \n", cls_report)

In [246]:
# 모델을 생성
logi = LogisticRegression(max_iter=2000, random_state=42)
eval_clf(logi, x_train, y_train, x_test, y_test, "Logistic")

Logistic모델의 정확도는 :  0.739
Logistic모델의 report :
               precision    recall  f1-score   support

           0       0.73      0.75      0.74       502
           1       0.74      0.72      0.73       498

    accuracy                           0.74      1000
   macro avg       0.74      0.74      0.74      1000
weighted avg       0.74      0.74      0.74      1000

In [250]:
svc2 = LinearSVC(random_state=42)
eval_clf(svc2, x_train, y_train , x_test, y_test, 'LinearSVC')

LinearSVC모델의 정확도는 :  0.737
LinearSVC모델의 report :
               precision    recall  f1-score   support

           0       0.73      0.75      0.74       502
           1       0.74      0.72      0.73       498

    accuracy                           0.74      1000
   macro avg       0.74      0.74      0.74      1000
weighted avg       0.74      0.74      0.74      1000