### Openapi
- 데이터를 제공하는 주소와 요청 시 필요한 데이터들을 요청 메세지에 추가하여 요청(request)
- 필요한 데이터들과 주소를 명확하다면 응답 메시지 반환
- 서버에게 요청을 보내는 라이브러리 : requests
    - requests에 내장된 get() 함수를 이용하여 요청을 보내고 응답 메세지를 받는다.

In [1]:
import requests

In [6]:
url = 'https://apis.data.go.kr/B190001/salesPolicy'
service_key = 'dtbWOdJ/Cz5HE0DGLU+CRPe7pOW0NIQBUcGEqsHZaTRiYCI/5+zugwzQjcvuId7NPdg6rUiW+ft3fm7yqyD4pw=='
sub_url = '/paper'

params = {
    'serviceKey' : service_key,
    'pageNo' : 1,
    'numOfRows' : 10
}

res = requests.get(url+sub_url, params)

In [7]:
res

In [8]:
res.content

b'{"currentCount":10,"data":[{"corp_dscnt_prchs_yn":"Y","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":100000,"mm_prchs_lmt_amt":10010,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"11110","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"Y","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":10000000,"mm_prchs_lmt_amt":500000,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"52750","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"N","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240201","dscnt_plcy_aplcn_end_ymd":"20240229","dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"Y","max_dscnt_lmt_amt":500000,"max_excng_lmt_amt":999999999,"mm_prchs_lmt_amt":400000,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"46860","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"N","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":10000000,"mm_prchs_lmt_amt":700000,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"47750","yr_prchs_lmt_amt":10000000},{"corp_dscnt_prchs_yn":"N","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":999999999,"mm_prchs_lmt_amt":500000,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"46790","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"N","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":0,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":999999999,"mm_prchs_lmt_amt":0,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"51790","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"N","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":0,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":0,"mm_prchs_lmt_amt":0,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"51130","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"Y","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":20000000,"mm_prchs_lmt_amt":500000,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"44250","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"N","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240201","dscnt_plcy_aplcn_end_ymd":"20240229","dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"Y","max_dscnt_lmt_amt":500000,"max_excng_lmt_amt":10000000,"mm_prchs_lmt_amt":300000,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"48730","yr_prchs_lmt_amt":0},{"corp_dscnt_prchs_yn":"N","corp_smpl_prchs_yn":"Y","crtr_ymd":"20240201","dscnt_plcy_aplcn_bgng_ymd":"20240101","dscnt_plcy_aplcn_end_ymd":null,"dscnt_rt":10,"dy_prchs_lmt_amt":0,"expt_plcy_yn":"N","max_dscnt_lmt_amt":null,"max_excng_lmt_amt":10000000,"mm_prchs_lmt_amt":500000,"pvsn_inst_cd":"I0000004","usage_rgn_cd":"47760","yr_prchs_lmt_amt":4000000}],"matchCount":65920,"page":1,"perPage":10,"totalCount":65920}\n'

In [ ]:
import pandas as pd

In [20]:
# Bytes 타입의 데이터는 DataFrame 변환이 불가능
# json 형태의 데이터인 경우 -> json 라이브러리 호출
# json 라이브러리 안에 loads() 함수를 이용하여 데이터의 타입을 변환
import json
res_data = json.loads(res.content)

In [24]:
# res_data에는 데이터셋 뿐만이 아니라 요청에 대한 응답 결과들이 같이 포함
# 원하는 데이터셋만 따로 추출하여 데이터프레임화
df = pd.DataFrame(res_data['data'])
df2 = df.copy()

In [25]:
# 데이터프레임의 각각의 컬럼의 이름들은 api을 제공하는 사이트에서 확인하여 이름을 변경
# df.columns -> 전체 컬럼의 이름을 변경 (class의 속성의 값을 변경)
# df.rename() -> 함수를 이용하여 컬럼의 이름을 변경 (class의 메서드를 이용하여 내부의 데이터를 변경)
df.columns = ['법인할인구매가능여부', '법인단순구매가능여부', '기준일자', '할인정책적용시작일자', '할일정책종료일자', '할인율', '일간구매제한금액', '예외정책여부', '최대할인제한금액', '최대환전제한금액', '월간구매제한금액', \
    '제공기관코드', '사용처지역코드', '연간구매제한금액']

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   법인할인구매가능여부  10 non-null     object
 1   법인단순구매가능여부  10 non-null     object
 2   기준일자        10 non-null     object
 3   할인정책적용시작일자  10 non-null     object
 4   할일정책종료일자    2 non-null      object
 5   할인율         10 non-null     int64
 6   일간구매제한금액    10 non-null     int64
 7   예외정책여부      10 non-null     object
 8   최대할인제한금액    2 non-null      float64
 9   최대환전제한금액    10 non-null     int64
 10  월간구매제한금액    10 non-null     int64
 11  제공기관코드      10 non-null     object
 12  사용처지역코드     10 non-null     object
 13  연간구매제한금액    10 non-null     int64
dtypes: float64(1), int64(5), object(8)
memory usage: 1.2+ KB

In [28]:
cols = df2.columns
new_cols = ['법인할인구매가능여부', '법인단순구매가능여부', '기준일자', '할인정책적용시작일자', '할일정책종료일자', '할인율', '일간구매제한금액', '예외정책여부', '최대할인제한금액', '최대환전제한금액', '월간구매제한금액', \
    '제공기관코드', '사용처지역코드', '연간구매제한금액']

In [29]:
cols_dict = {}
for old, new in zip(cols, new_cols):
    cols_dict[old] = new

In [30]:
cols_dict

{'corp_dscnt_prchs_yn': '법인할인구매가능여부',
 'corp_smpl_prchs_yn': '법인단순구매가능여부',
 'crtr_ymd': '기준일자',
 'dscnt_plcy_aplcn_bgng_ymd': '할인정책적용시작일자',
 'dscnt_plcy_aplcn_end_ymd': '할일정책종료일자',
 'dscnt_rt': '할인율',
 'dy_prchs_lmt_amt': '일간구매제한금액',
 'expt_plcy_yn': '예외정책여부',
 'max_dscnt_lmt_amt': '최대할인제한금액',
 'max_excng_lmt_amt': '최대환전제한금액',
 'mm_prchs_lmt_amt': '월간구매제한금액',
 'pvsn_inst_cd': '제공기관코드',
 'usage_rgn_cd': '사용처지역코드',
 'yr_prchs_lmt_amt': '연간구매제한금액'}

In [31]:
# rename 함수를 이용하여 컬럼의 이름을 변경
# rename 함수의 장점 : 인덱스나 컬럼이나 모두 변경이 가능, 속성의 값을 변환할 때는 확인 불가능하지만 rename은 확인하고 변환이 가능
df2.rename(columns= cols_dict)

,법인할인구매가능여부,법인단순구매가능여부,기준일자,할인정책적용시작일자,할일정책종료일자,할인율,일간구매제한금액,예외정책여부,최대할인제한금액,최대환전제한금액,월간구매제한금액,제공기관코드,사용처지역코드,연간구매제한금액
0,Y,Y,20240201,20240101,None,10,0,N,NaN,100000,10010,I0000004,11110,0
1,Y,Y,20240201,20240101,None,10,0,N,NaN,10000000,500000,I0000004,52750,0
2,N,Y,20240201,20240201,20240229,10,0,Y,500000.0,999999999,400000,I0000004,46860,0
3,N,Y,20240201,20240101,None,10,0,N,NaN,10000000,700000,I0000004,47750,10000000
4,N,Y,20240201,20240101,None,10,0,N,NaN,999999999,500000,I0000004,46790,0
5,N,Y,20240201,20240101,None,0,0,N,NaN,999999999,0,I0000004,51790,0
6,N,Y,20240201,20240101,None,0,0,N,NaN,0,0,I0000004,51130,0
7,Y,Y,20240201,20240101,None,10,0,N,NaN,20000000,500000,I0000004,44250,0
8,N,Y,20240201,20240201,20240229,10,0,Y,500000.0,10000000,300000,I0000004,48730,0
9,N,Y,20240201,20240101,None,10,0,N,NaN,10000000,500000,I0000004,47760,4000000

In [39]:
import os 
# 특정 경로에 파일이 존재하는가?

# 존재유무판단-> is 
# 파일 -> file

if os.path.isfile("./test.csv"):
    # 특정 경로에 파일이 존재하는 경우
    # 해당 파일에 데이터를 추가 
    # 데이터프레임에서 인덱스 저장x 헤더(머리 부분의 데이터 -> 컬럼명) 저장x
    df.to_csv('./test.csv', index=False, mode='a', header=False)
else:
    # 파일이 존재하지 않는 경우 
    # 파일을 새로 생성하여 헤더는 저장o, 인덱스는 저장x
    df.to_csv('./test.csv', index=False)
# mode 매개변수 
    # 'w'(기본값) : 기존의 파일이 존재한다면 대체, 없으면 생성
    # 'a' : 기존의 파일에 데이터를 추가 
    # 'x' : 기존이 파일이 존재한다면 대입하지 않겠다.(기존의 파일을 보존)

In [44]:
service_key2 = '6546674f4664617237314274704d75'
service_name = 'LOCALDATA_082604_SM'
data_type = 'xml'
start_idx = '1'
end_idx = '10'

url2 = f'http://openapi.seoul.go.kr:8088/{service_key2}/{data_type}/{service_name}/{start_idx}/{end_idx}/'

In [45]:
res2 = requests.get(url2)

In [46]:
res2.content

b'<?xml version="1.0" encoding="UTF-8"?>\n<LOCALDATA_082604_SM>\n<list_total_count>17515</list_total_count>\n<RESULT>\n<CODE>INFO-000</CODE>\n<MESSAGE>\xec\xa0\x95\xec\x83\x81 \xec\xb2\x98\xeb\xa6\xac\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4</MESSAGE>\n</RESULT>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200033</MGTNO>\n<APVPERMYMD>2002-08-28</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>03</TRDSTATEGBN>\n<TRDSTATENM>\xed\x8f\x90\xec\x97\x85</TRDSTATENM>\n<DTLSTATEGBN>03</DTLSTATEGBN>\n<DTLSTATENM>\xed\x8f\x90\xec\x97\x85\xec\xb2\x98\xeb\xa6\xac</DTLSTATENM>\n<DCBYMD>2012-12-12</DCBYMD>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>362-6328</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO>120-170</SITEPOSTNO>\n<SITEWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\x8c\x80\xed\x98\x84\xeb\x8f\x99 **\xeb\xb2\x88\xec\xa7\x80 **\xed\x98\xb8</SITEWHLADDR>\n<RDNWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x8b\xa0\xec\xb4\x8c\xeb\xa1\x9c *** (\xeb\x8c\x80\xed\x98\x84\xeb\x8f\x99)</RDNWHLADDR>\n<RDNPOSTNO>120-170</RDNPOSTNO>\n<BPLCNM>\xea\xb8\xb0\xed\x94\x84\xed\x8a\xb8\xeb\x8b\xb7\xec\xbb\xb4</BPLCNM>\n<LASTMODTS>2012-12-12 14:35:57</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2022-04-22 00:22:33.0</UPDATEDT>\n<UPTAENM>-</UPTAENM>\n<X>195214.990355229    </X>\n<Y>450530.472512122    </Y>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM/>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200042</MGTNO>\n<APVPERMYMD>2002-09-03</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>04</TRDSTATEGBN>\n<TRDSTATENM>\xec\xb7\xa8\xec\x86\x8c/\xeb\xa7\x90\xec\x86\x8c/\xeb\xa7\x8c\xeb\xa3\x8c/\xec\xa0\x95\xec\xa7\x80/\xec\xa4\x91\xec\xa7\x80</TRDSTATENM>\n<DTLSTATEGBN>07</DTLSTATEGBN>\n<DTLSTATENM>\xec\xa7\x81\xea\xb6\x8c\xeb\xa7\x90\xec\x86\x8c</DTLSTATENM>\n<DCBYMD/>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>02  394   3216</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO/>\n<SITEWHLADDR>\xed\x99\x8d\xec\x9d\x80\xeb\x8f\x99***-**\xec\x98\x81\xec\x8b\xa0\xeb\xb9\x8c\xeb\x9d\xbc***</SITEWHLADDR>\n<RDNWHLADDR/>\n<RDNPOSTNO/>\n<BPLCNM>VOVOS</BPLCNM>\n<LASTMODTS>2013-02-20 17:55:28</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2022-04-22 00:22:33.0</UPDATEDT>\n<UPTAENM>-</UPTAENM>\n<X/>\n<Y/>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM/>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200062</MGTNO>\n<APVPERMYMD>2002-09-16</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>03</TRDSTATEGBN>\n<TRDSTATENM>\xed\x8f\x90\xec\x97\x85</TRDSTATENM>\n<DTLSTATEGBN>03</DTLSTATEGBN>\n<DTLSTATENM>\xed\x8f\x90\xec\x97\x85\xec\xb2\x98\xeb\xa6\xac</DTLSTATENM>\n<DCBYMD>2008-02-01</DCBYMD>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>02  396   6531</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO/>\n<SITEWHLADDR>\xed\x99\x8d\xec\xa0\x9c\xeb\x8f\x99**-* ***\xed\x98\xb8</SITEWHLADDR>\n<RDNWHLADDR/>\n<RDNPOSTNO/>\n<BPLCNM>\xec\x9d\xb4\xeb\xa1\xac\xeb\x9d\xbc\xec\x9d\xb4\xed\x94\x84\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xec\xa4\x91\xec\x95\x99\xec\xa7\x80\xec\x82\xac</BPLCNM>\n<LASTMODTS>2011-12-26 13:35:52</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2022-04-22 00:22:33.0</UPDATEDT>\n<UPTAENM>-</UPTAENM>\n<X/>\n<Y/>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM/>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200080</MGTNO>\n<APVPERMYMD>2001-12-20</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>03</TRDSTATEGBN>\n<TRDSTATENM>\xed\x8f\x90\xec\x97\x85</TRDSTATENM>\n<DTLSTATEGBN>03</DTLSTATEGBN>\n<DTLSTATENM>\xed\x8f\x90\xec\x97\x85\xec\xb2\x98\xeb\xa6\xac</DTLSTATENM>\n<DCBYMD>2007-08-28</DCBYMD>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>02  363   8494</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO>110-035</SITEPOSTNO>\n<SITEWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xec\x98\xa5\xec\x9d\xb8\xeb\x8f\x99 **\xeb\xb2\x88\xec\xa7\x80 **\xed\x98\xb8 \xec\x98\xa5\xec\x9d\xb8\xeb\xb9\x8c\xeb\x94\xa9 *\xec\xb8\xb5</SITEWHLADDR>\n<RDNWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xec\x9e\x90\xed\x95\x98\xeb\xac\xb8\xeb\xa1\x9c ** (\xec\x98\xa5\xec\x9d\xb8\xeb\x8f\x99,\xec\x98\xa5\xec\x9d\xb8\xeb\xb9\x8c\xeb\x94\xa9 *\xec\xb8\xb5)</RDNWHLADDR>\n<RDNPOSTNO/>\n<BPLCNM>(\xec\xa3\xbc)\xed\x94\x84\xeb\xa0\x88\xec\x8b\x9c\xec\x95\x88</BPLCNM>\n<LASTMODTS>2007-08-28 16:09:48</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2022-04-22 00:22:33.0</UPDATEDT>\n<UPTAENM>-</UPTAENM>\n<X>197316.790897542    </X>\n<Y>453287.92068054     </Y>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM/>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200085</MGTNO>\n<APVPERMYMD>2000-04-14</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>01</TRDSTATEGBN>\n<TRDSTATENM>\xec\x98\x81\xec\x97\x85/\xec\xa0\x95\xec\x83\x81</TRDSTATENM>\n<DTLSTATEGBN>01</DTLSTATEGBN>\n<DTLSTATENM>\xec\xa0\x95\xec\x83\x81\xec\x98\x81\xec\x97\x85</DTLSTATENM>\n<DCBYMD/>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>02  393   0700</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO/>\n<SITEWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\x8c\x80\xed\x98\x84\xeb\x8f\x99 **\xeb\xb2\x88\xec\xa7\x80 **\xed\x98\xb8</SITEWHLADDR>\n<RDNWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x9d\xb4\xed\x99\x94\xec\x97\xac\xeb\x8c\x80\xea\xb8\xb8 ** (\xeb\x8c\x80\xed\x98\x84\xeb\x8f\x99)</RDNWHLADDR>\n<RDNPOSTNO>03766</RDNPOSTNO>\n<BPLCNM>\xeb\x86\x8d\xec\x97\x85\xed\x9a\x8c\xec\x82\xac\xeb\xb2\x95\xec\x9d\xb8 \xec\xa3\xbc\xec\x8b\x9d\xed\x9a\x8c\xec\x82\xac \xec\x98\x88\xec\x82\x90\xec\x9b\x90\xec\x98\x88</BPLCNM>\n<LASTMODTS>2019-10-22 14:22:04</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2019-10-24 00:22:57.0</UPDATEDT>\n<UPTAENM>\xea\xb8\xb0\xed\x83\x80</UPTAENM>\n<X>195125.659700742    </X>\n<Y>450688.154142148    </Y>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM>\xec\x9d\xb8\xed\x84\xb0\xeb\x84\xb7</SILMETNM>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200091</MGTNO>\n<APVPERMYMD>2001-07-09</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>03</TRDSTATEGBN>\n<TRDSTATENM>\xed\x8f\x90\xec\x97\x85</TRDSTATENM>\n<DTLSTATEGBN>03</DTLSTATEGBN>\n<DTLSTATENM>\xed\x8f\x90\xec\x97\x85\xec\xb2\x98\xeb\xa6\xac</DTLSTATENM>\n<DCBYMD>2009-12-28</DCBYMD>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>02  303   4411</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO/>\n<SITEWHLADDR>\xeb\x82\xa8\xea\xb0\x80\xec\xa2\x8c\xeb\x8f\x99***-*</SITEWHLADDR>\n<RDNWHLADDR/>\n<RDNPOSTNO/>\n<BPLCNM>\xec\x9d\x80\xed\x8f\x89\xec\xa0\x95\xeb\xb3\xb4\xed\x86\xb5\xec\x8b\xa0</BPLCNM>\n<LASTMODTS>2009-12-28 09:57:36</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2022-04-22 00:22:33.0</UPDATEDT>\n<UPTAENM>-</UPTAENM>\n<X/>\n<Y/>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM/>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200096</MGTNO>\n<APVPERMYMD>2001-11-28</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>03</TRDSTATEGBN>\n<TRDSTATENM>\xed\x8f\x90\xec\x97\x85</TRDSTATENM>\n<DTLSTATEGBN>03</DTLSTATEGBN>\n<DTLSTATENM>\xed\x8f\x90\xec\x97\x85\xec\xb2\x98\xeb\xa6\xac</DTLSTATENM>\n<DCBYMD>2016-11-18</DCBYMD>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>305-6063</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO>120-131</SITEPOSTNO>\n<SITEWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\xb6\x81\xea\xb0\x80\xec\xa2\x8c*\xeb\x8f\x99 ***\xeb\xb2\x88\xec\xa7\x80 *\xed\x98\xb8</SITEWHLADDR>\n<RDNWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x9d\x91\xec\x95\x94\xeb\xa1\x9c *** (\xeb\xb6\x81\xea\xb0\x80\xec\xa2\x8c\xeb\x8f\x99)</RDNWHLADDR>\n<RDNPOSTNO>120-131</RDNPOSTNO>\n<BPLCNM>(\xec\xa3\xbc)\xeb\xaf\xb8\xeb\x9e\x98\xec\x99\x80\xec\x9a\xb0\xec\xa3\xbc</BPLCNM>\n<LASTMODTS>2016-11-18 14:09:34</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2018-08-31 23:59:59.0</UPDATEDT>\n<UPTAENM>\xea\xb0\x80\xec\xa0\x84</UPTAENM>\n<X>192359.530890607    </X>\n<Y>453474.882927471    </Y>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM>\xec\x9d\xb8\xed\x84\xb0\xeb\x84\xb7</SILMETNM>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200109</MGTNO>\n<APVPERMYMD>1999-10-02</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>01</TRDSTATEGBN>\n<TRDSTATENM>\xec\x98\x81\xec\x97\x85/\xec\xa0\x95\xec\x83\x81</TRDSTATENM>\n<DTLSTATEGBN>01</DTLSTATEGBN>\n<DTLSTATENM>\xec\xa0\x95\xec\x83\x81\xec\x98\x81\xec\x97\x85</DTLSTATENM>\n<DCBYMD/>\n<CLGSTDT>2003-05-09</CLGSTDT>\n<CLGENDDT>2004-11-05</CLGENDDT>\n<ROPNYMD/>\n<SITETEL>02  393   4822</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO/>\n<SITEWHLADDR>\xed\x95\xa9\xeb\x8f\x99**-*</SITEWHLADDR>\n<RDNWHLADDR/>\n<RDNPOSTNO/>\n<BPLCNM>\xe3\x88\x9c\xed\x8e\x9c.\xea\xb7\xb8\xeb\xa6\xac\xea\xb3\xa0 \xec\x9e\x90\xec\x9c\xa0</BPLCNM>\n<LASTMODTS>2008-02-21 00:00:00</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2022-04-22 00:22:33.0</UPDATEDT>\n<UPTAENM>-</UPTAENM>\n<X/>\n<Y/>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM/>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200111</MGTNO>\n<APVPERMYMD>2002-04-17</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>03</TRDSTATEGBN>\n<TRDSTATENM>\xed\x8f\x90\xec\x97\x85</TRDSTATENM>\n<DTLSTATEGBN>03</DTLSTATEGBN>\n<DTLSTATENM>\xed\x8f\x90\xec\x97\x85\xec\xb2\x98\xeb\xa6\xac</DTLSTATENM>\n<DCBYMD>2013-12-30</DCBYMD>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>02  392   3200</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO/>\n<SITEWHLADDR>\xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99**-** *\xec\xb8\xb5</SITEWHLADDR>\n<RDNWHLADDR/>\n<RDNPOSTNO/>\n<BPLCNM>\xec\xa3\xbc\xec\x8b\x9d\xed\x9a\x8c\xec\x82\xac \xed\x81\xac\xeb\xa0\x88\xeb\xa7\x88\xec\xbb\xa4\xed\x94\xbc\xec\xbb\xb4\xed\x8e\x98\xeb\x8b\x88</BPLCNM>\n<LASTMODTS>2013-12-30 18:15:10</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2022-04-22 00:22:33.0</UPDATEDT>\n<UPTAENM>-</UPTAENM>\n<X/>\n<Y/>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM/>\n</row>\n<row>\n<OPNSFTEAMCODE>3120000</OPNSFTEAMCODE>\n<MGTNO>2002312010723200119</MGTNO>\n<APVPERMYMD>2002-05-17</APVPERMYMD>\n<APVCANCELYMD/>\n<TRDSTATEGBN>01</TRDSTATEGBN>\n<TRDSTATENM>\xec\x98\x81\xec\x97\x85/\xec\xa0\x95\xec\x83\x81</TRDSTATENM>\n<DTLSTATEGBN>01</DTLSTATEGBN>\n<DTLSTATENM>\xec\xa0\x95\xec\x83\x81\xec\x98\x81\xec\x97\x85</DTLSTATENM>\n<DCBYMD/>\n<CLGSTDT/>\n<CLGENDDT/>\n<ROPNYMD/>\n<SITETEL>335-1521</SITETEL>\n<SITEAREA/>\n<SITEPOSTNO>120-110</SITEPOSTNO>\n<SITEWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x97\xb0\xed\x9d\xac\xeb\x8f\x99 ***\xeb\xb2\x88\xec\xa7\x80 ***\xed\x98\xb8 \xec\x9e\xac\xec\x9d\xb4\xec\x86\x90\xeb\xb9\x8c\xeb\x94\xa9 ***\xed\x98\xb8</SITEWHLADDR>\n<RDNWHLADDR>\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x97\xb0\xed\x9d\xac\xeb\xa1\x9c **, ***\xed\x98\xb8 (\xec\x97\xb0\xed\x9d\xac\xeb\x8f\x99)</RDNWHLADDR>\n<RDNPOSTNO>120-830</RDNPOSTNO>\n<BPLCNM>\xec\x9e\xac\xec\x9d\xb4\xec\x86\x90\xec\x82\xb0\xec\x97\x85(\xec\xa3\xbc)</BPLCNM>\n<LASTMODTS>2012-12-07 16:22:02</LASTMODTS>\n<UPDATEGBN>I</UPDATEGBN>\n<UPDATEDT>2018-08-31 23:59:59.0</UPDATEDT>\n<UPTAENM>\xeb\xa0\x88\xec\xa0\xb8/\xec\x97\xac\xed\x96\x89/\xea\xb3\xb5\xec\x97\xb0</UPTAENM>\n<X>193559.689489602    </X>\n<Y>451122.684993594    </Y>\n<ASETSCP>0</ASETSCP>\n<BCTOTAM>0</BCTOTAM>\n<CAPT>0</CAPT>\n<SILMETNM>\xec\x9d\xb8\xed\x84\xb0\xeb\x84\xb7</SILMETNM>\n</row>\n</LOCALDATA_082604_SM>\n'

In [49]:
# !pip install xmltodict

In [50]:
# res2의 데이터는 xml 형태로 데이터 확인
# 익숙한 데이터 타입인 dict형태로 데이터 변환 -> 해당 기능을 가진 라이브러리 호출
import xmltodict

In [51]:
# xml 형태인 바이트 데이터를 dict 형태로 변환
# xmltodict에 내장된 parse()함수를 이용
data = xmltodict.parse(res2.content)

In [68]:
df3 = pd.DataFrame(data['LOCALDATA_082604_SM']['row'])
df3.head()

,OPNSFTEAMCODE,MGTNO,APVPERMYMD,APVCANCELYMD,TRDSTATEGBN,TRDSTATENM,DTLSTATEGBN,DTLSTATENM,DCBYMD,CLGSTDT,...,LASTMODTS,UPDATEGBN,UPDATEDT,UPTAENM,X,Y,ASETSCP,BCTOTAM,CAPT,SILMETNM
0,3120000,2002312010723200033,2002-08-28,None,03,폐업,03,폐업처리,2012-12-12,None,...,2012-12-12 14:35:57,I,2022-04-22 00:22:33.0,-,195214.990355229,450530.472512122,0,0,0,None
1,3120000,2002312010723200042,2002-09-03,None,04,취소/말소/만료/정지/중지,07,직권말소,None,None,...,2013-02-20 17:55:28,I,2022-04-22 00:22:33.0,-,None,None,0,0,0,None
2,3120000,2002312010723200062,2002-09-16,None,03,폐업,03,폐업처리,2008-02-01,None,...,2011-12-26 13:35:52,I,2022-04-22 00:22:33.0,-,None,None,0,0,0,None
3,3120000,2002312010723200080,2001-12-20,None,03,폐업,03,폐업처리,2007-08-28,None,...,2007-08-28 16:09:48,I,2022-04-22 00:22:33.0,-,197316.790897542,453287.92068054,0,0,0,None
4,3120000,2002312010723200085,2000-04-14,None,01,영업/정상,01,정상영업,None,None,...,2019-10-22 14:22:04,I,2019-10-24 00:22:57.0,기타,195125.659700742,450688.154142148,0,0,0,인터넷

In [69]:
if os.path.isfile("./서울시서대문통신판매업인허가현황.csv"):
    df3.to_csv('./서울시서대문통신판매업인허가현황.csv', index=False, mode='a', header=False)
else:
    df3.to_csv('./서울시서대문통신판매업인허가현황.csv', index=False)

In [66]:
from pprint import pprint

In [67]:
pprint(data)

{'LOCALDATA_082604_SM': {'RESULT': {'CODE': 'INFO-000',
                                    'MESSAGE': '정상 처리되었습니다'},
                         'list_total_count': '17515',
                         'row': [{'APVCANCELYMD': None,
                                  'APVPERMYMD': '2002-08-28',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '기프트닷컴',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': '2012-12-12',
                                  'DTLSTATEGBN': '03',
                                  'DTLSTATENM': '폐업처리',
                                  'LASTMODTS': '2012-12-12 14:35:57',
                                  'MGTNO': '2002312010723200033',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': '120-170',
                                  'RDNWHLADDR': '서울특별시 서대문구 신촌로 *** (대현동)',
                                  'ROPNYMD': None,
                                  'SILMETNM': None,
                                  'SITEAREA': None,
                                  'SITEPOSTNO': '120-170',
                                  'SITETEL': '362-6328',
                                  'SITEWHLADDR': '서울특별시 서대문구 대현동 **번지 **호',
                                  'TRDSTATEGBN': '03',
                                  'TRDSTATENM': '폐업',
                                  'UPDATEDT': '2022-04-22 00:22:33.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '-',
                                  'X': '195214.990355229',
                                  'Y': '450530.472512122'},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2002-09-03',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': 'VOVOS',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': None,
                                  'DTLSTATEGBN': '07',
                                  'DTLSTATENM': '직권말소',
                                  'LASTMODTS': '2013-02-20 17:55:28',
                                  'MGTNO': '2002312010723200042',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': None,
                                  'RDNWHLADDR': None,
                                  'ROPNYMD': None,
                                  'SILMETNM': None,
                                  'SITEAREA': None,
                                  'SITEPOSTNO': None,
                                  'SITETEL': '02  394   3216',
                                  'SITEWHLADDR': '홍은동***-**영신빌라***',
                                  'TRDSTATEGBN': '04',
                                  'TRDSTATENM': '취소/말소/만료/정지/중지',
                                  'UPDATEDT': '2022-04-22 00:22:33.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '-',
                                  'X': None,
                                  'Y': None},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2002-09-16',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '이롬라이프서대문중앙지사',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': '2008-02-01',
                                  'DTLSTATEGBN': '03',
                                  'DTLSTATENM': '폐업처리',
                                  'LASTMODTS': '2011-12-26 13:35:52',
                                  'MGTNO': '2002312010723200062',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': None,
                                  'RDNWHLADDR': None,
                                  'ROPNYMD': None,
                                  'SILMETNM': None,
                                  'SITEAREA': None,
                                  'SITEPOSTNO': None,
                                  'SITETEL': '02  396   6531',
                                  'SITEWHLADDR': '홍제동**-* ***호',
                                  'TRDSTATEGBN': '03',
                                  'TRDSTATENM': '폐업',
                                  'UPDATEDT': '2022-04-22 00:22:33.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '-',
                                  'X': None,
                                  'Y': None},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2001-12-20',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '(주)프레시안',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': '2007-08-28',
                                  'DTLSTATEGBN': '03',
                                  'DTLSTATENM': '폐업처리',
                                  'LASTMODTS': '2007-08-28 16:09:48',
                                  'MGTNO': '2002312010723200080',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': None,
                                  'RDNWHLADDR': '서울특별시 종로구 자하문로 ** (옥인동,옥인빌딩 '
                                                '*층)',
                                  'ROPNYMD': None,
                                  'SILMETNM': None,
                                  'SITEAREA': None,
                                  'SITEPOSTNO': '110-035',
                                  'SITETEL': '02  363   8494',
                                  'SITEWHLADDR': '서울특별시 종로구 옥인동 **번지 **호 옥인빌딩 '
                                                 '*층',
                                  'TRDSTATEGBN': '03',
                                  'TRDSTATENM': '폐업',
                                  'UPDATEDT': '2022-04-22 00:22:33.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '-',
                                  'X': '197316.790897542',
                                  'Y': '453287.92068054'},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2000-04-14',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '농업회사법인 주식회사 예삐원예',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': None,
                                  'DTLSTATEGBN': '01',
                                  'DTLSTATENM': '정상영업',
                                  'LASTMODTS': '2019-10-22 14:22:04',
                                  'MGTNO': '2002312010723200085',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': '03766',
                                  'RDNWHLADDR': '서울특별시 서대문구 이화여대길 ** (대현동)',
                                  'ROPNYMD': None,
                                  'SILMETNM': '인터넷',
                                  'SITEAREA': None,
                                  'SITEPOSTNO': None,
                                  'SITETEL': '02  393   0700',
                                  'SITEWHLADDR': '서울특별시 서대문구 대현동 **번지 **호',
                                  'TRDSTATEGBN': '01',
                                  'TRDSTATENM': '영업/정상',
                                  'UPDATEDT': '2019-10-24 00:22:57.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '기타',
                                  'X': '195125.659700742',
                                  'Y': '450688.154142148'},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2001-07-09',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '은평정보통신',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': '2009-12-28',
                                  'DTLSTATEGBN': '03',
                                  'DTLSTATENM': '폐업처리',
                                  'LASTMODTS': '2009-12-28 09:57:36',
                                  'MGTNO': '2002312010723200091',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': None,
                                  'RDNWHLADDR': None,
                                  'ROPNYMD': None,
                                  'SILMETNM': None,
                                  'SITEAREA': None,
                                  'SITEPOSTNO': None,
                                  'SITETEL': '02  303   4411',
                                  'SITEWHLADDR': '남가좌동***-*',
                                  'TRDSTATEGBN': '03',
                                  'TRDSTATENM': '폐업',
                                  'UPDATEDT': '2022-04-22 00:22:33.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '-',
                                  'X': None,
                                  'Y': None},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2001-11-28',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '(주)미래와우주',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': '2016-11-18',
                                  'DTLSTATEGBN': '03',
                                  'DTLSTATENM': '폐업처리',
                                  'LASTMODTS': '2016-11-18 14:09:34',
                                  'MGTNO': '2002312010723200096',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': '120-131',
                                  'RDNWHLADDR': '서울특별시 서대문구 응암로 *** (북가좌동)',
                                  'ROPNYMD': None,
                                  'SILMETNM': '인터넷',
                                  'SITEAREA': None,
                                  'SITEPOSTNO': '120-131',
                                  'SITETEL': '305-6063',
                                  'SITEWHLADDR': '서울특별시 서대문구 북가좌*동 ***번지 *호',
                                  'TRDSTATEGBN': '03',
                                  'TRDSTATENM': '폐업',
                                  'UPDATEDT': '2018-08-31 23:59:59.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '가전',
                                  'X': '192359.530890607',
                                  'Y': '453474.882927471'},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '1999-10-02',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '㈜펜.그리고 자유',
                                  'CAPT': '0',
                                  'CLGENDDT': '2004-11-05',
                                  'CLGSTDT': '2003-05-09',
                                  'DCBYMD': None,
                                  'DTLSTATEGBN': '01',
                                  'DTLSTATENM': '정상영업',
                                  'LASTMODTS': '2008-02-21 00:00:00',
                                  'MGTNO': '2002312010723200109',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': None,
                                  'RDNWHLADDR': None,
                                  'ROPNYMD': None,
                                  'SILMETNM': None,
                                  'SITEAREA': None,
                                  'SITEPOSTNO': None,
                                  'SITETEL': '02  393   4822',
                                  'SITEWHLADDR': '합동**-*',
                                  'TRDSTATEGBN': '01',
                                  'TRDSTATENM': '영업/정상',
                                  'UPDATEDT': '2022-04-22 00:22:33.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '-',
                                  'X': None,
                                  'Y': None},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2002-04-17',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '주식회사 크레마커피컴페니',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': '2013-12-30',
                                  'DTLSTATEGBN': '03',
                                  'DTLSTATENM': '폐업처리',
                                  'LASTMODTS': '2013-12-30 18:15:10',
                                  'MGTNO': '2002312010723200111',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': None,
                                  'RDNWHLADDR': None,
                                  'ROPNYMD': None,
                                  'SILMETNM': None,
                                  'SITEAREA': None,
                                  'SITEPOSTNO': None,
                                  'SITETEL': '02  392   3200',
                                  'SITEWHLADDR': '신촌동**-** *층',
                                  'TRDSTATEGBN': '03',
                                  'TRDSTATENM': '폐업',
                                  'UPDATEDT': '2022-04-22 00:22:33.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '-',
                                  'X': None,
                                  'Y': None},
                                 {'APVCANCELYMD': None,
                                  'APVPERMYMD': '2002-05-17',
                                  'ASETSCP': '0',
                                  'BCTOTAM': '0',
                                  'BPLCNM': '재이손산업(주)',
                                  'CAPT': '0',
                                  'CLGENDDT': None,
                                  'CLGSTDT': None,
                                  'DCBYMD': None,
                                  'DTLSTATEGBN': '01',
                                  'DTLSTATENM': '정상영업',
                                  'LASTMODTS': '2012-12-07 16:22:02',
                                  'MGTNO': '2002312010723200119',
                                  'OPNSFTEAMCODE': '3120000',
                                  'RDNPOSTNO': '120-830',
                                  'RDNWHLADDR': '서울특별시 서대문구 연희로 **, ***호 (연희동)',
                                  'ROPNYMD': None,
                                  'SILMETNM': '인터넷',
                                  'SITEAREA': None,
                                  'SITEPOSTNO': '120-110',
                                  'SITETEL': '335-1521',
                                  'SITEWHLADDR': '서울특별시 서대문구 연희동 ***번지 ***호 '
                                                 '재이손빌딩 ***호',
                                  'TRDSTATEGBN': '01',
                                  'TRDSTATENM': '영업/정상',
                                  'UPDATEDT': '2018-08-31 23:59:59.0',
                                  'UPDATEGBN': 'I',
                                  'UPTAENM': '레져/여행/공연',
                                  'X': '193559.689489602',
                                  'Y': '451122.684993594'}]}}

In [ ]:
# 자체적인 DataBase에 저장
# 1. 각 행의 데이터들을 insert query 문을 이용하여 대입
# 2. sqlalchemy 라이브러리를 이용하여 DBserver와의 연결을 하고 to_sql()을 이용하여 데이터프레임 전체를 테이블에 대입(테이블이 존재하는 경우 -> 교체, 추가 / 테이블이 존재하지 않을때는 테이블생성)

In [70]:
# 데이터베이스에 연결
import pymysql

In [73]:
# service_key, DB Server 정보들은 외부 노출시 보안상 큰 문제가 발생
# .env에 데이터를 저장하고 외부에 해당 파일은 업로드 하지 않는다. (일반적인 방법)
# dotenv 라이브러리를 이용해서 .env의 데이터를 가져온다.
# !pip install python-dotenv

In [74]:
from dotenv import load_dotenv
import os

In [75]:
# load_env() -> 작업 공간에 있는 .env 파일을 환경 변수에 등록
# os 라이브러리 -> 시스템 환경변수에 접근하기 위해 로드

In [76]:
load_dotenv()

True

In [78]:
# 환경 변수에서 서버의 정보를 불러온다.
os.getenv('port')

'3306'

In [80]:
# DB Server에 연결 (connect)
db = pymysql.connect(
    host = os.getenv('host'),
    port = int(os.getenv('port')),
    user = os.getenv('user'),
    password=os.getenv('pw'),
    db = os.getenv('db_name')
)

In [81]:
# pyton환경과 DB server 환경 사이에 가상의 공간(corsor)을 생성
# cursor() -> 기본값으로 사용하면 쿼리의 결과를 tuple 형태로 되돌려줌
# DictCursor를 사용하면 dict 형태를 되돌려궂ㅁ
cursor = db.cursor(pymysql.cursors.DictCursor)

In [ ]:
# 기존의 데이터블을 제거
# drop_query = "DROP TABLE test_data"
# cursor.execute(drop_query)

0

In [107]:
# 수집한 데이터를 저장하기 위해 저장할 공간(table)을 생성
# table은 엑셀파일과 같다라고 생각

# table을 생성하는 query문 -> CREATE문 -> table이나 Database를 생성할때 사용하는 query문
create_query = """
    CREATE TABLE test
    (
        a varchar(32) primary key,
        b varchar(32) not null
    )

"""

# df3의 컬럼의 개수가 29개 이므로 
query_head = "CREATE TABLE  if not exists test_data ("
query_tail = ")"

for col in df3.columns:
    # print(col)
    text = f"{col} varchar(40),"
    # print(text)
    
    # text를 query_head에 누적합
    query_head += text
query = query_head[:-1] + query_tail

In [108]:
# Query문을 cursor에 보낸다.
# 질의를 보낸다.(execute())
cursor.execute(query)

0

In [109]:
# 데이털를 입력 -> insert into table명(필드명, ...) values (데이터 ,...)
# 모든 필드에서 데이터를 대입하는 경우
# insrt into table valeus (데이터, ...)
insert_query = "INSERT INTO test_data VALUES ("
end_str = ")"
for i in range(len(df3.columns)):
    insert_query += "%s,"
    
insert_query = insert_query[:-1] + end_str

In [110]:
# df3의 모든 values를 문자로 변환
df3 = df3.astype(str)

In [111]:
# execute(quert, ?에 들어갈 데이터) 함수를 이용해서 쿼리문을 cursor에 보낸다.
cursor.execute(insert_query, list(df3.loc[0].values))

1

In [114]:
# df3의 오늘 인덱스의 데이터들을 insert문을 이용하여 대입
for idx in df3.index:
    # 만약에 primary_key 지정된 필드에 같은 데이터가 대입이 되면 에러
    # 중복 에러
    try:
        cursor.execute(insert_query,
                    list(df3.loc[idx].values))
    except:
        # 중복 에러가 발생시 실행되는 부분
        print('중복 데이터 관리')

In [115]:
# cursor와 db server 동기화
db.commit()

### 데이터프레임을 DBserver에 즉각 대입
- sqlalchemy , pandas 라이브러리 사용
    - sqlalchemy 내장된 create_engine 함수를 이용
    - pandas의 DataFrame에서 to_sql() 함수를 이용
        - 필수 매개변수
            - name
                - 테이블 이름을 지정
            - con
                - 데이터베이스 서버의 정보 (create_engine)
        - 선택 매개변수
            -index
                - 기본값 : True
                - index의 데이터를 포함할 것인가
            - if_exists
                - 기본값 : fail
                - replace -> 데이터의 내용을 변경
                - append -> 데이터를 추가
                - fail -> 실패 처리

In [116]:
from sqlalchemy import create_engine

In [117]:
# create_engine 함수를 이용하여 서버의 정보를 저장
# "{DB종류}+{DB연결라이브러리}://{DBuser명}:{비밀번호}@{DBhost}:{port}/{DataBase명}"
engine = create_engine(
    'mysql+pymysql://root:1234@localhost:3306/multicam'
)

In [118]:
df3.to_sql(
    name = 'test_data2',
    con=engine,
    index=False
)

10